### ISSUE TITLE
Standards for Warnings / Errors / Info

### ISSUE THREAD

**Issue by brandonskerritt** [RustScan/RustScan#120]
I came across this project:
![image](https://user-images.githubusercontent.com/10378052/89406821-9efeb880-d715-11ea-88bd-a90cbdd53d42.png)
And I liked the use of `[!]` in red to signify a warning / error.

RustScan currently highlights the whole text in a colour, and  the text is quite long.

Preferably:
- [ ] come up with colours for warnings / errors / info
- [ ] Do not colour the whole line, just the start
- [ ] Remove the new lines so only the useful info stays
- [ ] Clean up file description limit warnings so they're not giant chunks of text

**Comment by Yogendra0Sharma** [comment]
@brandonskerritt can i work on this issue ?

**Comment by brandonskerritt** [comment]
> @brandonskerritt can i work on this issue ?

Sure! :D

**Comment by smackhack** [comment]
We can follow a similar system to the example project @brandonskerrit linked, where every output has a specific category and quick symbol to denote the purpose of the message, along with their own color coding for the symbol only to quickly identify/categorize it without coloring the entire line.

Here's a rough guideline for one, that we can adopt.
From above:
`[ ! ]` - Errors/Alerts, colored red
`[>]` - Output, colored green
`[~]` - Detail (omitted unless -v is used), colored blue

For errors- should be specifically anything that could compromise the function of the program, such as outdated version, unoptimal or dangerous configurations, and any sort of panic.

Output should obviously only be the key output details that users want to see, such as open ports found.

Details are only present when -v is used, and should be the smaller steps of the programs and various debug info.

Any thoughts on this?

**Comment by brandonskerritt** [comment]
We need to print out useful info, such as where the config file should be if it wasn't found. This is currently printed in yellow, which category would this fall under?

**Comment by smackhack** [comment]
We could add a new category for alerts that are possibly important, but not fatal/required, perhaps a `[?]` or `[*]` colored yellow maybe?

**Comment by brandonskerritt** [comment]
Done!
