### ISSUE TITLE
Automatically resolve hostname

### ISSUE THREAD

**Issue by tomelic** [RustScan/RustScan#122]
**Is your feature request related to a problem? Please describe.**
Quite a simple one - let us input hostnames instead of just IP's :)

**Describe the solution you'd like**
Resolve hostname with the corresponding rust library and scan the first IP that was resolved

**Describe alternatives you've considered**
I manually do it for my automations, would enjoy this automation for this repo.

**Comment by brandonskerritt** [comment]
This looks promising 
https://crates.io/crates/dns-lookup
While we're re-vamping IPs I'll make sure to include it :)

**Comment by bernardoamc** [comment]
Fixed by #152
