### ISSUE TITLE
Support for Subnets and Top Ports

### ISSUE THREAD

**Issue by Anon-7** [RustScan/RustScan#124]
**Is your feature request related to a problem? Please describe.**
Scanning limited to single IP only. Targeting specific ports not supported.

**Describe the solution you'd like**
Support IP ranges, subnets and IP list (.txt) as an input. Furthermore, support scanning of top ports (e.g. 100, 5000 .etc). Top ports list is opensource.

**Additional context**
Already impressed with scanning speed. Thumbs up.

**Comment by brandonskerritt** [comment]
Hey! Thanks for your kind words.

* As of 1.6, you can scan multiple IP addresses https://github.com/RustScan/RustScan/releases/tag/1.6.0 **This is incredibly early. See #34 for current work**. We expect this to be done in 1 week to support sub-ranges, CIDR, file input, and more.
* Top ports is also being worked on right now. See #69 

Thanks again for your kind words! If you have anything else you'd like to see, please feel free to make another comment :D
