### ISSUE TITLE
Add support for proxy chains / Tor

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#139]
RustScan is very horrible to use through a Proxychain / Tor, from what I've heard

# Comment from people
it's a tool that forces an app to transfer all traffic through proxy
i.e proxychains rustscan IP
But that's extremely slow

And yeah, it took a good two hours before I cancelled it

**Comment by fdellwing** [comment]
Instead of relying on ugly and slow proxychains, you could add direct socks5 support, that will perform much better.
