### ISSUE TITLE
False comparison

### ISSUE THREAD

**Issue by noraj** [RustScan/RustScan#141]
The comparison of time execution between rustcan vs nmap is totally wrong.

![image](https://user-images.githubusercontent.com/16578570/89777613-50359200-db0c-11ea-9ffd-0fa817681fd3.png)

It claims that rustcan scans 65535 ports in 39 seconds and nmap in 17 minutes and 41 seconds.
But rustscan only check for open ports and in the nmap output you didn't launch nmap with `-p-` only but with `-A -p-` so with all options including service discovery, hast discovery, NSE scripts, OS probing, etc. so the comparison is totally biased since it's not even comparing the same thing. And even if RusScan ask for NSE scripts afterward it's still now asking for everything else.
Also it should compare with `-sS -p-` since SYN scan are way faster than the default TCP scan that require acknowledgement.

IF rustscan is just wrapping nmap and openning one thread by port to scan it's no different from something like that `seq 1 65535 | xargs -P 50 -I port  nmap -p port -sT -T4 10.42.42.2 -Pn -n`.

Also nmap documentation itself says its a bad idea and it's less fast and accurate https://nmap.org/book/reduce-scantime.html

> # Execute Concurrent Nmap Instances
>
>Some people try to speed up Nmap by executing many copies in parallel against one target each. For example, the Nessus scanner used to do this by default. This is usually much less efficient and slower than letting Nmap run against the whole network. Nmap has its own parallelization system that is customized to its needs, and Nmap is able to speed up as it learns about network reliability when it scans a large group. Further, there is substantial overhead in asking the OS to fork 65,536 separate Nmap instances just to scan a class B. Having dozens of copies of Nmap running in parallel is also a memory drain since each instance loads its own copy of the data files such as nmap-services and nmap-os-db.
>
>While launching single-host Nmap scans in parallel is a bad idea, overall speed can usually be improved by dividing the scan into several large groups and executing those concurrently. Don't go overboard though. Five or ten Nmap processes are fine, but launching 100 Nmap processes at once is not recommended. Launching too many concurrent Nmap processes leads to resource contention. Another sort of concurrency is to run Nmap from different hosts at once. You can have cron (or At on Windows) schedule local hosts on each of your networks to start scanning machines local to them at the same time, then mail the results to a central data server. Scanning your Australian network from the U.S. will be slower than scanning it from a local machine on that network. The difference will be even greater if the U.S. machine must traverse extra firewalls to reach the distant network.

At least rustscan should use `-b 100` by default and not `-b 5000`. Anyway 5000 is a good may to make both the attacker and the target machine crash  so what's the point in having such a high number as default?

**Comment by brandonskerritt** [comment]
Hey!

thanks for the comment. 

RustScan does not "open one thread by port".

Also it's not Rustscan Vs Nmap. It's Nmap with RustScan Vs Nmap on its own.

That's an incredibly intricate command. The whole point of RustScan is to be simple to use :) I can't imagine any newbies wanting to use a command that long 😂

Also, that documentation doesn't apply to us because we don't do that? we run 1 nmap instance?

Thanks for your feedback but I'm closing this issue ✨ The only thing that I'll consider is the comparison, because it should be more clearly marked as nmap with Rustscan Vs one single nmap scan (which it is, in the documentation but I take it people don't read that 😅✨✨)
