### ISSUE TITLE
nmap flag -A is always added, which is not expected based on the documentation

### ISSUE THREAD

**Issue by Arnonymous2** [RustScan/RustScan#154]
**Describe the bug**
The behavior of the nmap scan is not as expected / described on: https://github.com/RustScan/RustScan#-nmap-custom-flags

_RustScan automatically runs nmap -vvv -p $PORTS $IP. To make it run -A, execute the command rustscan 127.0.0.1 -- -A._
It looks like the -A flag is added in all cases, also if you don't add -A. I would not expect this, especially if you add different flags and don't want the aggressive (and time consuming) scan.

**To Reproduce**
1. Start rustscan with :
```rustscan 127.0.0.1 -b 1000 -t 500 --ulimit 5000 -- -sV -sT -Pn```
2. The output is:
[>] The Nmap command to be run is nmap -sV -sT -Pn **-A** -p 34648,55016,22 127.0.0.1

**Expected behavior**
nmap -sV -sT -Pn -p 34648,55016,22 127.0.0.1
without the **-A**  tags added.

**Screenshots**
![rustscan-nmap-A](https://user-images.githubusercontent.com/67524603/90319575-b9b50680-df39-11ea-9725-52ce7ed7ad49.png)

**Desktop (please complete the following information):**
Tested on kali linux with the version: rustscan_1.7.1_amd64.deb

**Additional context**
Already mentioned the issue on Discord, and @kaeros agreed this is not expected behavior.
I guess this is the line where it happens: https://github.com/RustScan/RustScan/blob/master/src/main.rs#L218

**Comment by brandonskerritt** [comment]
Fixed in #160 , thank you! :D
