### ISSUE TITLE
Benchmark is running nmap in throttled mode

### ISSUE THREAD

**Issue by kpcyrd** [RustScan/RustScan#157]
Hello!

It seems nmap is slow for you, and I was surprised that RustScan is much faster. I've had a quick look at the source and it seems you're trying to fully saturate bandwidth, which nmap can also do. The nmap defaults explicitly throttle scan speed for reliability and safety reasons. It might also fall back to a slower connect scan if you're lacking permissions.

Please try to use the following options for a fair comparison (make sure you have CAP_NET_RAW):
```
nmap -sS -T insane -A -p- scanme.nmap.org
```

`-T insane` is the fastest mode possible but discouraged and you should probably use `-T4` instead to avoid issues like #125. `-T4` is mentioned in an example at the very top of `man nmap`.

Please consider to be more respectful of the nmap project in your readme, if you can outrun nmap with a connect scan you're probably using nmap incorrectly.

Thanks! <3

**Comment by Edu4rdSHL** [comment]
Even using -T4 `nmap` is faster if you adjust `--min-rate` :) all the ports were scanned in [6 seconds](https://twitter.com/FindomainApp/status/1292824781495177217) using `--max-retries 2` to avoid missing ports.

**Comment by brandonskerritt** [comment]
Hey!

This isn't nmap vs rustscan, it's nmap with rustscan vs without. <3
