### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by caass** [RustScan/RustScan#171]
**Is your feature request related to a problem? Please describe.**
Even if it's slow, it'd be nice to have windows support so that this crate could be included in packages targeting cross-platform support.

**Describe the solution you'd like**
The issue currently preventing windows support is the use of [rlimit](https://crates.io/crates/rlimit), which does not support windows. By adding checks for windows systems and hardcoding ulimit, we may temporarily work around this. I believe [documentation exists](https://docs.microsoft.com/en-us/windows/win32/memory/memory-limits-for-windows-releases?redirectedfrom=MSDN) for setting resource limits on windows, however I'm not very familiar with this sort of low-level stuff so I can't say for sure that this is feasible. Even if it is, it may be outside the scope of this project.

**Describe alternatives you've considered**
My ultimate goal is to include RustScan in another Rust project, so while running via Docker would be useful if I was an end-user, it is ultimately too cumbersome to call docker from rust and then run RustScan via docker via rust. It would be much simpler if I could simply include the crate in my dependencies.

**Additional context**
See #168, which should hopefully close this issue.

**Comment by brandonskerritt** [comment]
This is currently blocked, as merely importing `rlimit` causes us to not support windows.

We will need to find a way to conditionally import a module.

Maybe using the type hinting causes the defect, but I don't think so? As it's just a data type.

**Comment by brandonskerritt** [comment]
@all-contributors please add @caass for distributions & packaging

**Comment by brandonskerritt** [comment]
ARE YOU KIDDING ME all-contributors that link literally says `Packaging` is a valid thing. Okay let's try this one last time :roll_eyes: 

@all-contributors please add @caass for Packaging, distribution, platforms, porting support to new platforms

**Comment by caass** [comment]
@brandonskerritt it looks like you can have [platform-specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies), I'm on mobile atm but if I can find any examples of this and how it impacts imports I'll post them here.

**Comment by brandonskerritt** [comment]
BTW, including RustScan in another project -- I am also working on a rustscan scripting engine right now for running scripts on found ports from RustScan (but after I fix this), if you want to be the first to use it let me know. The very first version will require scripts to be approved by me :D 

Okay, so we'd have to:

1. Make `rlimit` conditional in `cargo.toml`
2. Change all mentions of the type-hint `rlimit` to an integer (u32)
3. if not on windows, run ulimit but in the ulimit function change the integer to a u32

**Comment by brandonskerritt** [comment]
Update: I think this is working now. Pushing for CI to confirm whether our tests run on Windows.

**Comment by brandonskerritt** [comment]
Update: I forgot to do step 1.... I'll do it tomorrow :sweat:

**Comment by brandonskerritt** [comment]
@caass Can you check out the windows support branch and try it out yourself?

The tests _might_ be failing because the tests themselves require the very feature not used in Windows. 

If the branch works I can merge right now and create an issue to fix the tests later :)

**Comment by caass** [comment]
@brandonskerritt i don't have a windows machine atm, but it should work fine if i run RustScan from a VM right?
