### ISSUE TITLE
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/scanner/mod.rs:111:21

### ISSUE THREAD

**Issue by Xm17** [RustScan/RustScan#189]
config docker env,then run rustscan -q x.x.x.x

hint me 

thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/scanner/mod.rs:111:21

![image](https://user-images.githubusercontent.com/27048404/91785428-f40bec80-ec37-11ea-997d-dc6cc7409ad3.png)

**Comment by bernardoamc** [comment]
Thanks for the report @Xm17 . I think the `IP` should be the last argument, could you try putting `-b 2500` before it?

**Comment by Xm17** [comment]
@bernardoamc yes ,put `-b` before ip , it can operate normally,thinks

**Comment by bernardoamc** [comment]
Thanks @Xm17 :)

I'm tracking these issues in a separate issues, going to close this one. For more information: #211
