### ISSUE TITLE
Add CIDR support

### ISSUE THREAD

**Issue by subfission** [RustScan/RustScan#190]
It would be great if CIDR or network range support was included for fast local net review.  eg:

 `$ rustscan 192.168.1.1/24` or `$ rustscan 192.168.1.1-255`

Currently, you need to ping all network hosts, compile a comma separated host list, then call rustscan.  Although, this feature is already integrated into NMAP.

**Comment by bee-san** [comment]
Just came back from a short break :) 

https://docs.rs/cidr/0.1.0/cidr/struct.InetIterator.html

This looks like what we want :smile:

**Comment by bernardoamc** [comment]
Up for review. :)
