### ISSUE TITLE
Exponental Backoff to increase accuracy

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#191]
Some users are porting bad accuracy and having to run twice.
I suggested this simple algorithm (as a default):

```
if any of the top 1000 ports are not found:
    run exponential_backoff as a timing algorithm and re-scan the ports
```

A future feature would be to rescan all ports (if the user wants them).

One user asked for a rate limit, but not in seconds. So the user says "rate limit 1" and it makes it never go slower than 1. This means that 10 will be fastest. So a rate limit of 5 means "half the speed as fastest".
It is important this is somehow incorporated into the backoff algorithm, because if we do 1 second timeouts for 65,000 ports thats 65,000 seconds.

**Comment by shahar481** [comment]
Hey :D

I don't exactly get what you are asking for here.. If it fails to find an open port out of the top 1000, it will rerun the scan but with exponential backoff? Is it supposed to be a default feature or a flag? Seems a bit strange for it to scan the same port twice (network wise) as a default feature. 
I think finding why scans fail is the better approach for this (speaking from a standpoint that knows nothing about why it fails).

I'll look into it a bit in my free time. I'll check if I get failed scans too

**Comment by bee-san** [comment]
Hey! If you know a better way to make sure the scans don't fail, go ahead :D
