### ISSUE TITLE
Update links in README to reflect RustScan repo move to RustScan org

### ISSUE THREAD

**Issue by robellegate** [RustScan/RustScan#199]
### Proposed Change
Update all references of https://github.com/brandonskerritt/RustScan to https://github.com/RustScan/RustScan

**Comment by bee-san** [comment]
Thanks a lot for this! I'll make sure to update in my next PR :D

**Comment by bernardoamc** [comment]
I've updated most of the links on my last PR, we should still double check though. 😄

**Comment by bernardoamc** [comment]
I think we have tackled this along the way, let me know if someone pops up. <3
