### ISSUE TITLE
Disable nmap option triggers nmap anyway

### ISSUE THREAD

**Issue by subfission** [RustScan/RustScan#202]
**Describe the bug**
When running the latest version `rustscan 1.8.0`, the flag for disabling nmap transition seems to be ignored.

**To Reproduce**

1. `docker run -it --rm --name rustscan rustscan/rustscan:latest 192.168.1.1/24 -t 500 -b 5000 -r 1-1000 --no-nmap`
2. Observe the `Starting Nmap 7.80 ( https://nmap.org ) at 2020-09-10 04:14 UTC` following the open port report.

**Expected behavior**
I think the use of this flag should stop further execution of nmap and just report the output.

**Desktop (please complete the following information):**
 - OS: Docker on MacOS

**Comment by bee-san** [comment]
Our docker built hasn't been updating because the CI is failing, sorry for that! Will fix ASAP.

**Comment by CMNatic** [comment]
Whilst this isn't dismissing the bug in the slightest, you can use the `-q` flag to at least somewhat truncate the information given, making it great for logging, grepping etc. This flag doesn't seem to run nmap which is interesting.

![image](https://user-images.githubusercontent.com/4163116/93043603-3d056d00-f64a-11ea-8aa9-2e13434b4155.png)

## Example Usage:
Working on the latest dockerbuild `rustscan/rustscan:latest` (14/09/2020):
`docker run -it --rm --name rustscan1409 rustscan/rustscan:latest -q rustscan.cmnatic.co.uk`
 
Where you can see the results have been truncated and the discovered port numbers at the end like below:
![image](https://user-images.githubusercontent.com/4163116/93043807-d03ea280-f64a-11ea-863d-0ed1deed7402.png)

We're aware of a few issues in the current Master branch and are working on them over the oncoming days! Hopefully this is a helpful workaround until then @subfission

**Comment by subfission** [comment]
Curious, but when you run the -q option against an interative IP list, you are not told which IP has the ports available.  Is this the desired effect?

eg `docker run -it --rm --name rustscan1409 rustscan/rustscan:latest -q 192.168.1.1-255`

**Comment by CMNatic** [comment]
You need to be providing a range via the subnet's CIDR notation. Specifically in your command -q `192.168.1.1-255`

Let's break this down:
1) You're trying to scan the range of IP's starting from the first value (the 4th octet), you need to provide the address of the subnet - not a host address when scanning this way 😄 

2) You're providing what I assume is 255.255.255.0 subnet via `-255`. 
a) You're giving the range with a dash `-`, needs to be a forward slash `/`
b) You need to use the CIDR notation instead - in this case, it is `24` for that subnet

Example of the correct usage from above: `docker run -it --rm --name rustscan rustscan/rustscan:latest -q 192.168.1.0/24`

Hope this helps!

**Comment by CMNatic** [comment]
Better yet, here's a screenshot below illustrating what I mean: 
![image](https://user-images.githubusercontent.com/4163116/93282059-6c8cb480-f7c5-11ea-9a4c-c0c6926daefe.png)

Note here the red and green coloured boxes. The IP address of this machine is `10.0.0.2` and has a CIDR notation of `/24` for my subnet. If I wanted to scan other devices on my subnet, I need to provide the network address instead - as shown on the last command - I have changed it to `10.0.0.0/24`

**Comment by subfission** [comment]
That's not actually relevant to the question.  Check out this screenshot. Notice that ports are identified, but not showing which host they are associated with.
![image](https://user-images.githubusercontent.com/8132423/93382020-59ee9b80-f816-11ea-8540-dd8e96b29f1e.png)

**Comment by subfission** [comment]
Latest has it fixed!  Woot!
