### ISSUE TITLE
Command to pipe results into

### ISSUE THREAD

**Issue by XXXTheInternXXX** [RustScan/RustScan#207]
I think this would be a good command to run when RustScan finds its ports, it can be found below. Take the results of Rustscan and put it into the following: 

nmap --min-rate 4500 --max-rtt-timeout 1500ms -Pn -sV {Found Ports} -T5 {IP Address}

**Comment by bernardoamc** [comment]
Thanks for the suggestion @XXXTheInternXXX. With our script engine (coming soon) we will allow any kind of scripts to run after the scan is complete. Closing this one for now. <3
