### ISSUE TITLE
Automatic Performance Option Tuning

### ISSUE THREAD

**Issue by Jeff-Rowell** [RustScan/RustScan#209]
**Is your feature request related to a problem? Please describe.**
I had to run rustscan several different times to find a batchsize, ulimit, and timeout setting that rustscan would allow and finally run a scan on all ports. The error messaging would tell me to set the timeout limit to (2s) when it was already set to that value, or just give the same canned error message each time.

**Describe the solution you'd like**
It would be neat if rustscan could automatically fine-tune the batchsize, timeout, and ulimit options for optimal performance rather than returning a canned error message and relying on the user to get all the options right.

**Describe alternatives you've considered**
Just using nmap.

**Comment by bee-san** [comment]
Yup! You're right, it would be better for us to automatically tune the performance. We are investigating the best way to do this. Although all of our methods thus far require access to a server :sweat_smile:
