### ISSUE TITLE
Rustscan should take hosts file as input

### ISSUE THREAD

**Issue by ankushgoel27** [RustScan/RustScan#210]
**Is your feature request related to a problem? Please describe.**
I want to scan a large set of hosts, currently, it doesn't take a file as input for hosts to scan

**Describe the solution you'd like**
Nmap takes a file as input for hosts.

**Describe alternatives you've considered**
bash loop

**Additional context**

**Comment by bernardoamc** [comment]
Thanks for the issue @ankushgoel27 ! For now we can rely on https://github.com/RustScan/RustScan/wiki/Config-File in order to make this process a bit less painful, there you can set addresses with any of these formats: `IP`, `Host` or `CIDR`.
