### ISSUE TITLE
Adjust `-p` argument with a single port.

### ISSUE THREAD

**Issue by bernardoamc** [RustScan/RustScan#211]
## Bug

Right now the following command will fail: `-b 100 -p 80 127.0.0.1`.

The current alternatives are:

* `-b 100 -p 80, 127.0.0.1`
* `-p 80 -b 100 127.0.0.1`

**Comment by bernardoamc** [comment]
@bee-san @smackhack one of the maintainers of `structopt` explained what was happening here and it actually makes a lot of sense. We have two options from here:

1. Create a custom parser for this argument
2. Make address an optional instead of a positional argument, as in, accept `-a` or `--addresses` instead of accepting it at the end of the command line args.

Option 1 keeps our API as is, but increases the complexity of our software.

Any preferences?

**Comment by bee-san** [comment]
What would creating a custom parser imply? How much complexity would it bring?

Ideally we'd keep the current API as other port scanners use positional arguments and by adding it as an option we increase the complexity the user has to face to use RustScan.

**Comment by bernardoamc** [comment]
I think it wouldn't be too much, but I haven't tried implementing it yet. 

The benefit of doing with option `2` is also solving these kind of reports: https://github.com/RustScan/RustScan/issues/189, but that can be done by being extra clear on our Wiki that IP should be the last argument.

Let me take a stab at implementing a parser for this argument and I will have a more informed opinion soon. 😄

**Comment by bee-san** [comment]
We can run a vote on our GitHub issues and I'll ask around for some more information :) Let me link the issue back here.

**Comment by bee-san** [comment]
Looks like it's over, change addresses to:

> Make address an optional instead of a positional argument, as in, accept -a or --addresses instead of accepting it at the end of the command line args.

**Comment by bernardoamc** [comment]
I will tackle this along the week. :)
