### ISSUE TITLE
Provide a JSON output option

### ISSUE THREAD

**Issue by adrwh** [RustScan/RustScan#213]
**Describe the solution you'd like**
A typical use case for this data would be to ship to NMAP as designed, or one of many other systems, and therefore a command line option such as `--json-file ./output.json` would be fantastic.

One example use case might be to ship results of the port scan directly to Elasticsearch.

**Comment by frenchtoastbeer** [comment]
Yes please!  I don't care about saving to a file specifically, but I would like the option for at least one output option that I wouldn't have to write a custom parser for.

Another way I can think of accomplishing this would be to release a library instead, and let the consumer do it themselves using serde or something.

**Comment by eviltik** [comment]
suggestion : like amass tool, `--json-file -` should use stdout for output the json stream

**Comment by gcavalcante8808** [comment]
Looks like that was a proposition regarding json use in https://github.com/RustScan/RustScan/pull/277, but it got tainted by XML and other stuff and the PR was closed.

 Is there any plans or is still desireable to support JSON as an output option?

**Comment by ocervell** [comment]
+1 pleaaaaaaaaaase JSON lines / JSON support so I can pipe the output into jq into `<insert_awesome_sec_tool_here>`
