### ISSUE TITLE
RustScan has 2 logging crates

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#218]
```
log = "0.4.0"
env_logger = "0.7.1"
```

I think only 1 is needed, but I'm not sure what logging crate is used in the code.

**Comment by bergabman** [comment]
env_logger is a helper for the log crate to be able to initialize logging with environment variables. We need them both.


From the env_logger doc:

**In executables**
It must be added along with `log` to the project dependencies:
```
[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
```
`env_logger` must be initialized as early as possible in the project. After it's initialized, you can use the `log` macros to do actual logging.
