### ISSUE TITLE
UDP Scan

### ISSUE THREAD

**Issue by DanNegrea** [RustScan/RustScan#22]
More of a feature request: UDP port scanning is taking exponentially longer than TCP port scanning. 
Would your approach help reduce the scan time?

**Comment by brandonskerritt** [comment]
Hey @DanNegrea , it would reduce the time for sure but I don't currently support UDP (I think, anyway, unless the sockets library does and I don't know about it). But it's on the TO-DO list! :D

**Comment by cocoonkid** [comment]
UDP would be a great addition. I root for it here :flags:

**Comment by cocoonkid** [comment]
I am still rooting   flags :}

**Comment by fropert** [comment]
+1

**Comment by bee-san** [comment]
👋🏻 

The sockets library does support UDP:
https://doc.rust-lang.org/std/net/struct.UdpSocket.html

I think the PR would be a case of just doing an `if` statement and either doing TCP or UDP.

I'll timebox it for this weekend, not sure how to test but I'll figure it out :D

**Comment by BrendanGlancy** [comment]
@bee-san I've been working on this, did you ever get anywhere with it?

**Comment by bee-san** [comment]
> @bee-san I've been working on this, did you ever get anywhere with it?

Hey there!

I did not get anywhere with this, feel free to contribute! 🥳

**Comment by BrendanGlancy** [comment]
@bee-san I don't know if we should open a discussion or something, but what I am finding is that UDP scanning is a little bit more complicated than TCP scanning. I can submit a pull request with what I have now that works for like 60-70% of cases and is much faster than nmap -sU.

The part that is difficult on this is that, essentially, even if we did the 20 most common UDP ports and didn't mess with the wait time for the response, which seems to actually matter in a lot of the testing I did, we'd have to scan each port 20 times. Multiple this but 3 or 4 different timeout lengths and ...

Anyway, like I said I'm happy to submit a pull request, as I'd love some criticism on my shitty junior dev Rust code. But the goal of this would be more or less getting some feedback from people more knowledgable than me on the subject on how to improve this.

**Comment by bee-san** [comment]
> @bee-san I don't know if we should open a discussion or something, but what I am finding is that UDP scanning is a little bit more complicated than TCP scanning. I can submit a pull request with what I have now that works for like 60-70% of cases and is much faster than nmap -sU.
> 
> The part that is difficult on this is that, essentially, even if we did the 20 most common UDP ports and didn't mess with the wait time for the response, which seems to actually matter in a lot of the testing I did, we'd have to scan each port 20 times. Multiple this by 3 or 4 different timeout lengths and ...
> 
> Anyway, like I said I'm happy to submit a pull request, as I'd love some criticism on my shitty junior dev Rust code. But the goal of this would be more or less getting some feedback from people more knowledgeable than me on how to improve this.

Sure, submit the code! :) I'd love to read it!

**Comment by PsypherPunk** [comment]
Closing this as it was resolved in #596.
