### ISSUE TITLE
Adding practical CI tests for DockerHub Image

### ISSUE THREAD

**Issue by CMNatic** [RustScan/RustScan#223]
**Is your feature request related to a problem? Please describe.**
At the moment, the `rustscan/rustscan:latest` tag on DockerHub updates after a successful build on every merge into master. As it stands, the DockerHub just tests to see if cargo installs okay - there are no practical/example usage tests performed.

**Describe the solution you'd like**
When a commit is made into master, the trigger to update the `latest` tag should fire like normal, however, RustScan itself will be tested and put into another tag such as `rustscan/rustscan:stable`

**Describe alternatives you've considered**
Travis CI checks, however, doing these tests via Docker and DockerHub is a lot more effective because of the use of docker-compose.

**Additional context**
Rather than trusting that any commit to master should be assumed as fully tested i.e. arguments, we can check for results of an example scan. If the scan is successful, the `rustscan/rustscan:stable` will be updated.

This is going to be important as at the moment, the only CI for DockerHub is the trigger on commit to master.

**Comment by bee-san** [comment]
Still working on this?

**Comment by CMNatic** [comment]
Hi Bee, yes I am. It's slightly fallen through the net - my apologies. Now that I've implemented a better build process for DockerHub, we're always going to have a recent stable version. It's not super ideal as it stands.

However, now I can start to look into this alongside re-writing the Debian builder as discussed tonight to hopefully get Travis' involvement a lot more in building the `.deb` files across architectures

**Comment by CMNatic** [comment]
Conditions for this PR has been met with the changes made in DockerHub & PR #298 is really nice for the road ahead
