### ISSUE TITLE
DNS Resolver does not use OS' resolver

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#245]
**Describe the bug**
Per `trust_dns_resolver`'s documentation:
https://docs.rs/trust-dns-resolver/0.19.5/trust_dns_resolver/

> It does not use the Host OS' resolver. If what is desired is to use the Host OS' resolver, generally in the system's libc, then the std::net::ToSocketAddrs variant over &str should be used.

This causes some problems as with CTFs sometimes we have to change our hosts file to reach the target webpage. 

Also, it would be faster to use the OS' resolver than an external one.

**Comment by bee-san** [comment]
Opening this up to Hacktoberfest <3 Please leave a comment saying you want this and I'll assign you :D

**Comment by shahar481** [comment]
Hey :),
So basically you just want to replace all resolving you did with trust dns with to_socket_addrs?
I'll start working on it.

**Comment by bee-san** [comment]
> Hey :),
> So basically you just want to replace all resolving you did with trust dns with to_socket_addrs?
> I'll start working on it.

Hey! Sorry for not replying, I was asleep.

I didn't explain this issue very well, my bad. 

We want to keep both trust_dns but use `std::net::ToSocketAddrs` at the same time, I think.

The logic should be:

* Use `std::net::ToSocketAddrs` to check the host OS' resolver.
* If it didn't resolve:
    * Use Trust DNS

So we use the local Host Resolver on the PC (the hosts file, I believe it's called) but if it's not in there we use Trust DNS -- do you understand that? Or am I being confusing again. My bad! I'm quite tired right now :sweat_smile:

**Comment by shahar481** [comment]
Yeah I think I got it. You want trust-dns to be the fallback resolver if the OS couldn't resolve.

**Comment by shahar481** [comment]
Hey :D, 
Don't want to ping you too much. Just letting you know that I updated the PR.
