### ISSUE TITLE
Create benchmark tests using Criterion.rs

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#257]
# Problem

RustScan is designed to be fast, and to do this we need to benchmark our program. 

# Solution
https://github.com/bheisler/criterion.rs

Criterion is a Rust library for benchmarking code using a test.

## Things you need to know
* The address you should scan is `rustscan.cmnatic.co.uk`.
* The batch size and ulimit should be fixed (pick anything you want).
* It should scan all ports.

To use RustScan, observe one of the tests in the `scanner` directory. This is from `mod.rs`

```rust
    fn scanner_runs() {
        // Makes sure the program still runs and doesn't panic
        let addrs = vec!["127.0.0.1".parse::<IpAddr>().unwrap()];
        let range = PortRange {
            start: 1,
            end: 1_000,
        };
        let strategy = PortStrategy::pick(Some(range), None, ScanOrder::Serial);
        let scanner = Scanner::new(&addrs, 10, Duration::from_millis(100), true, strategy, true);
        block_on(scanner.run());
        // if the scan fails, it wouldn't be able to assert_eq! as it panicked!
        assert_eq!(1, 1);
    }
```

If you have any questions, please get in touch! :)

**Comment by MusiKid** [comment]
Hi!
I can work on it.

**Comment by bee-san** [comment]
> Hi!
> I can work on it.

Sure! :D

**Comment by MusiKid** [comment]
So I started to take a look at it and to use Criterion, the crate needs to not be a [binary one](https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html). We need to create a library to expose the required functions and I'm not sure if this is what we want.

**Comment by bee-san** [comment]
> So I started to take a look at it and to use Criterion, the crate needs to not be a [binary one](https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html). We need to create a library to expose the required functions and I'm not sure if this is what we want.

Yes that's very annoying.... I'll leave this open until we create some library / API we can use :P

**Comment by mdevlamynck** [comment]
For information I just found out https://github.com/sharkdp/hyperfine that can bench executables directly. Maybe that can be used in the meantime? (and maybe compare against nmap?)

**Comment by bee-san** [comment]
> For information I just found out https://github.com/sharkdp/hyperfine that can bench executables directly. Maybe that can be used in the meantime? (and maybe compare against nmap?)

This is VERY nice. Oh wow! JSON output!
https://github.com/sharkdp/hyperfine#export-results

@CMNatic Does your Grafana instance accept requests? I.E. can someone make a program to pipe the JSON results of this into your Grafana instance? :)

**Comment by MusiKid** [comment]
@mdevlamynck That would be possible, even if it wouldn't be as straightforward as using directly Criterion 🤷

**Comment by bee-san** [comment]
> @mdevlamynck That would be possible, even if it wouldn't be as straightforward as using directly Criterion shrug

Do you think creating a library would be easier? What functions do we want exposed? Just the actual scanning part?

I talked with @bernardoamc about this actually, we would like to expose the scanning as a function for some other purposes.

**Comment by bee-san** [comment]
Closing in favour of #262
