### ISSUE TITLE
Rustscan Overview and comparison

### ISSUE THREAD

**Issue by rootsploit** [RustScan/RustScan#269]
Hi there,

I have published a detailed blog on Rustscan and comparison with other open source port scanner
https://rootsploit.com/bug-bounty-recon-faster-port-scan/

Thank you.

**Comment by bernardoamc** [comment]
Thank you @rootsploit :)

We are also working to support scripts that can be triggered once `RustScan` detects that a certain port is open. This means that soon you will be able to say: "Run this custom script when port 22 is open, and this one for port 80 and 443" as opposed to only have `nmap` as an option.

**Comment by rootsploit** [comment]
That seems to be a good option to implement.

Also, I would like to suggest a feature that can scan ports of all list of IP/Hostnames and generate a list of HTTP/HTTPS URLs based on open ports.

For Eg: 
```
root@rustscan# cat domains.txt
target.com
admin.target.com
testing.target.com

root@rustscan# cat domains.txt | rustscan --https-out --silent
https://target.com/
https://target.com:8443/
http://admin.target.com:8080/
https://testing.target.com:2340/

root@rustscan# cat domains.txt | rustscan --https-out --service --silent
[ IIS 8.5 ] https://target.com/
[ Apache 2.4.3 ] https://target.com:8443/
[ Apache-Tomcat 8.5 ] http://admin.target.com:8080/
[ Unknown ] https://testing.target.com:2340/
```

Using the above example it would be really helpful for pentester to find all webservers and automate it.

**Comment by bee-san** [comment]
@all-contributors please add @rootsploit for blogging :)
