### ISSUE TITLE
Linting with `cargo clippy`

### ISSUE THREAD

**Issue by niklasmohrin** [RustScan/RustScan#276]
Hi everyone!

I saw that you guys already have `cargo fmt` set up as a workflow, which is great. I think the addition of linting as a Github workflow would be very nice and help even more to keep code quality up. Currently, there are some warnings when running `cargo clippy` that need to be fixed, but it shouldn't take very long. A workflow could be adapted from [the tealdeer repository](https://github.com/dbrgn/tealdeer/blob/151d014f5d0e48b6988774b9d41d0e8f241c510b/.github/workflows/ci.yml#L41).

If you guys agree, I could open a PR myself and fix the few warnings to get this started.

**Comment by bee-san** [comment]
Please PR them! :D
