### ISSUE TITLE
RLIMIT breaking change

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#283]
We have a breaking change on RLIMIT that means we cannot upgrade the package.

"Cannot find rlimit in package rlimit".

If anyone can take a look and see what the fix is, much appreciated :heart:

_Originally posted by @bee-san in https://github.com/RustScan/RustScan/pull/275#issuecomment-710144940_

**Comment by okrplay** [comment]
I'll take a look at this.

**Comment by u5surf** [comment]
@bee-san Hi Can I help this issue. 
It seems to easy to fix using RawRlimt
 instead of rlim.

https://docs.rs/rlimit/0.5.2/rlimit/type.RawRlim.html
