### ISSUE TITLE
Add tests for rustscan scripting engine

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#286]
The module lacks testing, but the example files in the `fixtures` directory can be used to write the tests. There is an example script config file and 4 different scripts to work with.

_Originally posted by @bergabman in https://github.com/RustScan/RustScan/pull/242#issuecomment-710767106_

RustScan scripting engine is missing essential tests. Using the 4 different example scripts we wrote, write some tests and PR them :) :sparkling_heart:

**Comment by okrplay** [comment]
I'll work on this.
