### ISSUE TITLE
Write CI that checks for specific outputs in the terminal

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#291]
RustScan has an accessible mode, `rustscan --accessible` which _should_ promise not to have any weird ASCII text in it.

Write CI that runs RustScan with `--accessible` **a few times, with different flags / options** and check the terminal output to see if it contains one of these:

1. `[!]`
2. `[~]`
3. `[>]`
4. `| {}`

If any of these characters appear in any of the tests, fail the CI. Else, pass the CI.

This is a hacktoberfest issue if you want it :sparkling_heart: and we're available in Discord or over GitHub to talk :smile:

**Comment by emhagman** [comment]
Is this still available? I wouldn't mind adding it but I realize this might be stale.

**Comment by facklambda** [comment]
Would this be better to make as a test that would fail if one of these outputs is found, thus causing the `cargo test` invocation in the CI action to fail?

**Comment by facklambda** [comment]
I'm going to try my hand at writing a test.

**Comment by renghen** [comment]
hi I want to do this one, is it a git action thing?
