### ISSUE TITLE
Resumable port scans

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#299]
Assume we are scanning a CIDR at a slow speed overnight. The internet dies and the scan stops. We have to try again from step 0.

I am suggesting 2 features:
1. Record the scan to a file and allow the scan to be "resumed", so we don't have to repeat the same scan on a host twice.
2. Automatically detect loss of internet (if no ports found on a single host, ping Google) and wait until internet is restored before resuming the port scan.

**Comment by gangov** [comment]
hey @bee-san I got a mockup, can I take this?
