### ISSUE TITLE
Only TCP port scanning?

### ISSUE THREAD

**Issue by RitamDey** [RustScan/RustScan#307]
Hey! I was reading the source-code to see how rustscan is so fast and I saw [this](https://github.com/RustScan/RustScan/blob/02f1f6c7d155f150787f1443030e5179119a2275/src/scanner/mod.rs#L162). I'm not familiar with rust but does this line indicate that rustscan only connects using TCP? Is there any plan for also including UDP scanning?

**Comment by bergabman** [comment]
Yes, currently we have only full `TCP` connection scan. Planning to implement `syn` scan and `UDP` as well in the future.

**Comment by RitamDey** [comment]
@bergabman Hey thanks!! I asked this because I made the TCP-only claim in a [write-up](https://stux.gitlab.io/vulnhub/me-and-my-girlfriend.html). Looking forward to **SYN** and **UDP** support. Closing the issue
