### ISSUE TITLE
argument which wasn't expected (ip address)

### ISSUE THREAD

**Issue by foozzi** [RustScan/RustScan#315]
**when I start rustscan with standard configurations, I get an argument error**
this problem happened after installing macos Big Sur. on the previous version of macos everything worked fine!

**To Reproduce**
1. just start ```rustscan 125.125.125.125```
2. See error:
```
error: Found argument '125.125.125.125' which wasn't expected, or isn't valid in this context

USAGE:
    rustscan [FLAGS] [OPTIONS] [-- <command>...]

For more information try --help
```

**Desktop:**
 - OS: MacOS Big Sur (v. 11.0.1)
 - rustscan 2.0.0

**Comment by jonathanwall** [comment]
rustscan 2.0 uses -a as the address flag now. so rustscan -a 125.125.125.125

**Comment by foozzi** [comment]
> rustscan 2.0 uses -a as the address flag now. so rustscan -a 125.125.125.125

oh, thank you... did not look at the changes

**Comment by jonathanwall** [comment]
> > rustscan 2.0 uses -a as the address flag now. so rustscan -a 125.125.125.125
> 
> oh, thank you... did not look at the changes

I had to join the discord to figure it out myself. I guess the docs will catch up.
