### ISSUE TITLE
The current --ports and --range parameters have hidden problems that conflict with each other, which will cause trouble to use

### ISSUE THREAD

**Issue by iiiusky** [RustScan/RustScan#321]
**Is your feature request related to a problem? Please describe.**

The current --ports and --range parameters have hidden problems that conflict with each other, which will cause trouble to use

**Describe the solution you'd like**

If I need to scan the 1-1024, 8090-9000 ports of a certain ip, and the individual ports 7001, 8080, in the current version I need to use the following commands to complete

--ports 7001,8080 --range 1-1024,8090-900

But the bad thing is that --ports and --range will conflict

**Describe alternatives you've considered**
In terms of specifying the scan port, the --ports parameter and the --range parameter can be combined into one without two different parameters, which will increase the difficulty of use. After being combined into one, the following types of input can be accepted, example:

-p 1-1024,7001,8080,8090-9000

**Additional context**

**Comment by slayernominee** [comment]
it would be also great if it is possible to make something like

-p -300,4000-

that stands for the first port up to the 300th port and 4000 to the last port
