### ISSUE TITLE
Why does rustscan sometimes sleep all 65535 ports of which do not exist?

### ISSUE THREAD

**Issue by foozzi** [RustScan/RustScan#324]
Why does rustscan sometimes sleep all 65535 ports of which do not exist?

**Comment by Hritish42** [comment]
Can you provide steps to reproduce the above issue?

> Why does rustscan sometimes sleep all 65535 ports of which do not exist?

**Comment by foozzi** [comment]
> Can you provide steps to reproduce the above issue?
> 
> > Why does rustscan sometimes sleep all 65535 ports of which do not exist?
just:

rustscan --ulimit 5000 --range 65535 -a <some_port>
