### ISSUE TITLE
how did you calculate the full scan in 3 seconds?

### ISSUE THREAD

**Issue by DeadNumbers** [RustScan/RustScan#328]
```
$ time rustscan -g -a 8.8.8.8 --ulimit 50000
8.8.8.8 -> [53,443,853]

real	0m22,692s
user	0m0,887s
sys	0m2,840s
```

**Comment by Hritish42** [comment]
Scan time varies with machine we're scanning and depends upon the arguments that we've supplied.

**Comment by Hritish42** [comment]
take

**Comment by DeadNumbers** [comment]
@Hritish42 lol

**Comment by bee-san** [comment]
@Hritish42 is correct :) 3 seconds is the maximum speed I have ever achieved, it is not the average.
