### ISSUE TITLE
Allow for multiple IP scanning

### ISSUE THREAD

**Issue by ophirharpaz** [RustScan/RustScan#34]
I think it'd be nice to be able to run _RustScan_ on multiple IPs, either through:

- stdin (comma-separated IPs?) 
- a file (as in nmap's `iL` flag).

Thanks for the nice tool! 🙏

**Comment by brandonskerritt** [comment]
Hey!! I totally agree with this. The code is actually there for this, just.... I need to connect it to the arguments list and do some quality of life stuff 😁✨

**Comment by sahadnk72** [comment]
Yeah, also support for CIDR notation would be great. For eg: 192.168.10.12/24

**Comment by brandonskerritt** [comment]
TO-DO:
- [ ] Allow for multiple ranges
Something like....

```
rustscan --ranges 10.10.10.* 10.10.19.*
```

**Comment by brandonskerritt** [comment]
Okay, I have a pretty good idea of _how_ to do this. Comment if you think I can improve.

* We have a queue data structure, and we place each IP address in this queue.
* We scan the IPs one-at-a-time based on this queue (we pop an IP out and scan it)

## Main
In main, specifically argparsing, we will have 3 methods of inputting IPs
* File input using `rustscan -- file.txt`
* Standard input (comma-seperated IPs) that includes wildcards "10.10.10.*" **and** CIDR "10.0.0.0/24"
* Through the config file #71 (this will come much later)

A function will take these inputs, and iterate over the IPs it contains pushing each one to the queue.

What do ya think? :)

**Comment by royharoush** [comment]
I think that if you can match all of Nmap target input possibilities both in file and the command line it will probably be easier for people to migrate from the masscan+nmap to rust-->nmap.

input types can include CIDRS (/24), and dynamic rangers (4-5.54-34.4.0-255), and and more. 
I dont mean to self promote, but I do have this little script that integrates masscan and and nmap together similar to what you do. 
it can found here:
https://gist.github.com/royharoush/4188a9547daf49e7d918ea86f5975ad6

my point stating it is that the only fault of masscan, and by extension my script, is that while it does randomize the hosts in masscan, it will still perform a host scan one at at time. 

I'm not familiar with rust, but I it would seem very straight-forward to perform a Rust fast scan against randomize ip-ports pairs as part of the main function for the rust scan, and then by extension, scan those in nmaps randomized results as well. 

you can see my super inefficient bash interpretation of this requirement here: 
https://github.com/royharoush/DistributedScanning/commit/c50cbc117a097fed30aeb398412f1c66b3620c76#diff-724d83c7d86962a7389dbc679231cb9dL108

 The only problem you would encounter is that you would need to create multiple nmap files, which pretty much !@#$s up every other nmap results parser\visualizer out there, but that's a problem in another project. 

Hope this input was useful and thank you for the great work !

**Comment by brandonskerritt** [comment]
Hey! Thanks so much for your input! :D 

Just to be clear, the 2 features you're suggesting are:
* Randomised IP + port scanning. So for the input:
```
10.10.10.1
10.10.10.2
```

The order of execution might look like:

```
10.10.10.1:27
10.10.10.2:6335
10.10.10.2:22
```

That's a good idea as it might convey less "noise" which seems to be everyones concern right now, as it's not strictly linear.

Not quite sure how I'll implement this efficiently. The fastest method I can imagine right now is is a hashmap where {IP: <Vec>} where `<Vec>` is a vector with 65535 length, and we insert `0` for closed and `1` for open in the right locations. It would take a lot of memory, and not very efficient -- but this is just my first thought.

For reference, the ports are randomised.... In the sense that it is async, and the order of execution is not guaranteed. 

The problem occurs when "randomised IP + ports" comes into play. 

I can do random ports easily, and random IP's easily too. But to combine random IP's and ports at the same time, I'd need some kind of data structure to keep track of things -- which is where it starts to get difficult :-(

2. Nmap files for output is a good idea. I can easily add this, as all I need to do is capture STD::OUT and redirect to a file as well as terminal usage. 

Thanks again for your suggestions! :D

**Comment by brandonskerritt** [comment]
@bernardoamc Don't suppose you have an idea on how to implement this better than mine? :)

**Comment by royharoush** [comment]
> 
> 
> Hey! Thanks so much for your input! :D
> 
> Just to be clear, the 2 features you're suggesting are:
> 
>     * Randomised IP + port scanning. So for the input:
> 
> 
> ```
> 10.10.10.1
> 10.10.10.2
> ```
> 
> The order of execution might look like:
> 
> ```
> 10.10.10.1:27
> 10.10.10.2:6335
> 10.10.10.2:22
> ```
> 
> That's a good idea as it might convey less "noise" which seems to be everyones concern right now, as it's not strictly linear.
> 
> Not quite sure how I'll implement this efficiently. The fastest method I can imagine right now is is a hashmap where {IP: } where `<Vec>` is a vector with 65535 length, and we insert `0` for closed and `1` for open in the right locations. It would take a lot of memory, and not very efficient -- but this is just my first thought.
> 
> For reference, the ports are randomised.... In the sense that it is async, and the order of execution is not guaranteed.
> 
> The problem occurs when "randomised IP + ports" comes into play.
> 
> I can do random ports easily, and random IP's easily too. But to combine random IP's and ports at the same time, I'd need some kind of data structure to keep track of things -- which is where it starts to get difficult :-(
> 
>     1. Nmap files for output is a good idea. I can easily add this, as all I need to do is capture STD::OUT and redirect to a file as well as terminal usage.
> 
> 
> Thanks again for your suggestions! :D

I think that nmap manages to keep memory usage down is in part by offloading results from memory to disk every amount of scan results returned. 
There's another nmap flag called --max\min-hostgroup, that that would set how many hosts will be scanned in a single batch, i guess you can use the same logical and play with the values untill you a reasonable memory usage. 
I have a feeling that randomizing ports over 5000 hosts at the time will give a good enough entropy while not killing memory. you can also provide a flag to support the "batch" size and specify anticipated memory usage for each memory size based on your testing. 
 
![image](https://user-images.githubusercontent.com/8113056/89104378-b5f59000-d421-11ea-9c5b-ac1f70eefab8.png)

hope that helps.

**Comment by bernardoamc** [comment]
My only concern is that this defeats the `batch_size` purpose. Assuming we still want to respect it we can randomize within ranges. 

Suppose we want to scan ports `1` to `1000` with a batch size of `200`. We can shuffle these five ranges [`1-200`, `201-400`, `401-600`, `601-800`, `801-1000`] and always start with a random range per `IP`.

So if we had: 

```
10.10.10.1
10.10.10.2
```

We might run something like:

```
10.10.10.1:601-800
10.10.10.2:401-600
...
10.10.10.2:601-800 # Notice the 2 at the end of the IP
...
# Until all the ranges for all IPs are covered.
```

And so on, covering all the ranges for all IPs.

This has the advantage that if people want more randomization per IP they can choose smaller batch sizes.

**Comment by brandonskerritt** [comment]
I suppose, as a data structure, we could possibly generate something like:

```
{IP: [0-65535]}
```

And then if we were to scan the range `601-800`, we fragment it like so:

```
{IP: [0-600, 801 - 65535]
```

And we stop when every IP has an empty list.

This has the advantage that we can easily specify ports in the first run, and can keep track of how "close" we are to finishing (how large the lists are, and how fast they shrink). 

If anyone knows of a more efficient data structure, please let me know :) The biggest concern to me is having a very inefficient data structure, which might ruin this entire feature :)

**Comment by royharoush** [comment]
you can take 2 files as arguments 
targets file
list of ports file (ranges, single ports), or accept --top-ports from nmap
i think that in order not to choke memory you can do the following: 
1. Flatten files into lists 
2. randomly create IP-Port into a temp file. 
3. based on batch size settings load those batch into execution and remove them from the temp file. 
4. rinse repeat untill the batchs are finished. 

I know this method isn't the cleanest .. but when you're a "bash" developer .. ;) 

It would make it easier to on memory and also would remove the code complexity so you don't need to relay on hashmaps and key value pairs, or at least not on recalculating them each time a batch is finished. 

if you want complexity you can write the ip-ports into an sqlite and remove the rows or add column(done\finished\failed), or even update the the result back into the sqlite file. the only problem i guess you would encounter is multiple writes by multiple threads into the same sqlite file.

**Comment by royharoush** [comment]
Here's a python script that creates this command list from an already flattend list of IPs and ports 
https://gist.github.com/royharoush/1926d9665e4fc218e30275b8f0ad2aee

**Comment by royharoush** [comment]
ok, you can scratch my above suggestion .. 
for /16 subnet with all ports the file that keeps the ip-port pair will be a few gb size and takes way too long to create.... :|

**Comment by bernardoamc** [comment]
Put some more thought around the issue and here's what I would start with:

Suppose we have 3 IPs with the following ranges:

* `IP1` -> `1-1000`
* `IP2` -> `1-65000`
* `IP3` -> `22, 80, 503, 8080`

Let's now assume the `batch_size` is `100` and I'm going to introduce something called `port_block_size` with a value of `10`.

**Algorithm:**
1. Iterate through every IP and get the amount of ports equal to the `port_block_size`.
    * IP1 -> `1-10`, IP2 -> `1-10`, IP3 -> `22, 80, 503, 8080`
2. Count the amount of ports, which is 24 in the example above.
3. While ports < `batch_size` keep computing the list.
    * [IP1 -> `1-10`, IP2 -> `1-10`, IP3 -> `22, 80, 503, 8080`, IP1 -> `11-20`, `IP2 -> `11-20`, ...]
4. When the amount of ports to be scanned reaches the batch size we spawn threads to hit the list.
5. Go back to step 1 and build a new list until all the ports are exhausted.

Properties of this algorithm:

1. Our memory footprint is always bounded by the `batch_size`
2. It always produces the same output given the same input
3. It always split the load between the amount of hosts specified

Extra:

1. We can shuffle the list on step 4 to randomize a bit the port scanning

**Comment by brandonskerritt** [comment]
@all-contributors please add @royharoush for ideas & design

^^ if the bot is working today, you'll be added to the README for your great contributions in this issue :sparkles:

**Comment by brandonskerritt** [comment]
My bad, the bot wasn't set up properly.
@all-contributors please add @royharoush for ideas & design

**Comment by royharoush** [comment]
I'm abit confused, sorry.

>     * `IP1` -> `1-1000`
> 
>     * `IP2` -> `1-65000`
> 
>     * `IP3` -> `22, 80, 503, 8080`

why would we different port ranges as input for different IPs ?
or was that not the starting point ? 

let's say we want to scan 10.10.0.0/16 with top 5k ports. 
so we have 327,825,000 (65535*5000) key value pairs to scan.
if we generate that list in memory ( "ip": "port") it will consume alot of memory, so there's need to be a way to randomly creating smaller batches.
what if we take take the larger input subnet(s), create smaller subnets (let's say 10.10.0.0/24), and randomly assigning these subnets with random ports ranges of up to 20 ports. and we exhaust that list. 
so let's say 256*5000 (1,275,000) is the amount of scans to be executed.  
by dividing the port list by 20 and assigning it to subnet i think (hope) we can maintain a small enough footprint, but still maintain proper randomization.

**Comment by bernardoamc** [comment]
> why would we different port ranges as input for different IPs ?

It would actually make implementation much easier if we don't need to support different ports for different IPs.

I would still keep the proposed implementation, but if we assume all the IPs will run the same ports we can allow randomized scanning. Here's the example:

```
IP1 -> 1-20
IP2 -> 1-20
IP3 -> 1-20
```

Let's say our `port_block_size` is `5`.

**Algorithm:**

1. Pick a random starting point in the range, let's say `10`.
2. Pick an end point in the range equals to `starting point` + `port_block_size`, which is `15`.
3. Scan all the IPs with randomized ports between `10` and `15`.
4. Go back to step 1 until all ports are exhausted.

**Comment by smackhack** [comment]
Instead of trying to keep a complex data structure of key:value pairs for keeping track of IP:port- which could result in massively large numbers of key value pairs once the scan gets complex/random enough, we could instead just have a single IP:port_bitmap instead, to keep track of exactly each port scanned while using the most compact data structure to be able to represent a large list of random bits without any excessive memory usage.

I think the most optimal way to store all of this data while keeping our memory footprint low (we even have further optimization routes by compacting the bitmap in some way, or finding another bitarray datastructure that automatically trims/prunes itself) as instead of using a hashmap which has a much larger memory footprint for storing keys and such, a bit array/vector can easily represent the entire range of 65535 ports in literally the densest most compact form of memory. Performing operations on it can also be easy as we can work with the bit array on an individual bit level.

(If you are unsure what a bit array/vector is, imagine a very long mutable string of binary)
i.e. a line of 0s and 1s the length of 65535, with `0` representing an unscanned port, and `1` representing a scanned port. Finding if port 443 was scanned would be as simple as checking if the 443rd bit is true or false.

**Comment by brandonskerritt** [comment]
> Instead of trying to keep a complex data structure of key:value pairs for keeping track of IP:port- which could result in massively large numbers of key value pairs once the scan gets complex/random enough, we could instead just have a single IP:port_bitmap instead, to keep track of exactly each port scanned while using the most compact data structure to be able to represent a large list of random bits without any excessive memory usage.
> 
> I think the most optimal way to store all of this data while keeping our memory footprint low (we even have further optimization routes by compacting the bitmap in some way, or finding another bitarray datastructure that automatically trims/prunes itself) as instead of using a hashmap which has a much larger memory footprint for storing keys and such, a bit array/vector can easily represent the entire range of 65535 ports in literally the densest most compact form of memory. Performing operations on it can also be easy as we can work with the bit array on an individual bit level.
> 
> (If you are unsure what a bit array/vector is, imagine a very long mutable string of binary)
> i.e. a line of 0s and 1s the length of 65535, with `0` representing an unscanned port, and `1` representing a scanned port. Finding if port 443 was scanned would be as simple as checking if the 443rd bit is true or false.

We should still store the result in something like a hashmap though, so we can return JSON for projects importing our code, or storing the JSON into a file :)

**Comment by smackhack** [comment]
> We should still store the result in something like a hashmap though, so we can return JSON for projects importing our code, or storing the JSON into a file :)

Definitely! We can easily convert it afterwards by translating the bitmap into a hashmap for other uses, but for the actual execution of the program, a bit array (since we don't need to worry about human readability or anything) definitely can store the data we need in the most compact and cheapest way, albeit at the cost of having to work with data at the bit level.

**Comment by brandonskerritt** [comment]
@bernardoamc What do you think of creating this as a single argument, rather than multiple? I like the idea of the user not having to memorise arguments / options:

```
rustscan <IPs>

* if ip contains /
> subnet
else if ip contains ,
> multiple ips (192.168.0.1, 192.168.0.2 and so on)
else if ip address converts to IpAddr:
> is IpAddr
else if file or config file:
> use them as input
else:
panic!
```

**Comment by bernardoamc** [comment]
> What do you think of creating this as a single argument, rather than multiple? I like the idea of the user not having to memorise arguments / options.

@brandonskerritt That's the first part of the implementation I'm going to tackle. We should have a PR tomorrow with it. :)

**Comment by royharoush** [comment]
@smackhack bitmap sounds like a great idea ! 
@brandonskerritt @bernardoamc I think we should provide the ability to provide a list of ports. a regular pentest\red team that involves service enumeration starts with smaller amount of pots (let's say top 500), and then you slowly increase the amount of ports you scan after you removed the hosts that can blacklist you. 

moving from one vps to another every 20 minutes because each time you scan you get blocked is no fun .. :) 
just a thought.

**Comment by brandonskerritt** [comment]
> @smackhack bitmap sounds like a great idea ! 
> @brandonskerritt @bernardoamc I think we should provide the ability to provide a list of ports. a regular pentest\red team that involves service enumeration starts with smaller amount of pots (let's say top 500), and then you slowly increase the amount of ports you scan after you removed the hosts that can blacklist you. 
> 
> moving from one vps to another every 20 minutes because each time you scan you get blocked is no fun .. :) 
> just a thought.  

I think you'll love what I'm working on the, as it's exactly this :)  let me know if you have any cool ideas for it too. https://github.com/RustScan/RustScan/issues/69

**Comment by bernardoamc** [comment]
Let's split this issue into smaller sub-issues and close this one as it's getting to tackle different ideas here.

**Right now we can:**

1. Scan multiple IPs through the command line
2. Scan those IPs with a random port order

**What we are tackling:**

1. Reading IPs and ports and whatnot from a configuration file

Any other issues we want to create? Keep the ideas coming @royharoush :)

**Comment by brandonskerritt** [comment]
Can we call the issue "2.0", and have it become our 2.0 release?

Here's how I have split down the config file:
1. Reading the config file [nearly done]
2. Automatic placement of config file [download it somehow so the user doesn't have to]
3. Read a single IP from config file
4. Read multiple IPs from config file
5. Read specific ports from config file (and somehow get RustScan to scan only those ports)
6. Top Ports in config file
7. A JSON object of IP: ports so RustScan only scans specific ports on specific IPs

**Comment by bernardoamc** [comment]
Sounds good to me. :)

**Comment by royharoush** [comment]
Hi Guys, do you have nightly builds somewhere so i can test most recent changes ?

**Comment by bernardoamc** [comment]
@royharoush I think the only way currently is to clone the repository and play with cargo itself.

* `cargo run -- <arguments>`

**Comment by bernardoamc** [comment]
Closing this one, we can open new issues with more specific features and flagging it as `feature request` or `good first issue` 😄
