### ISSUE TITLE
RustScan doesn't work with big number of IP addresses

### ISSUE THREAD

**Issue by amirnsahmad** [RustScan/RustScan#356]
Hello, how are you doing?

I used the masscan to scan big number of hosts, and i decided to change to rustscan. But some problems were found:

1. using docker: thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/scanner/mod.rs:138:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2. Using binary: 8 hours running and it doen't finish.

I am scanning 168 IPs.

Command: rustscan -t 5000 -b 5000 --scan-order Random --range 1-65535 -g -a [List_of_IPs]

**Comment by k0njac** [comment]
me too
