### ISSUE TITLE
Documentation: First table on docs page has escaped HTML content

### ISSUE THREAD

**Issue by zersiax** [RustScan/RustScan#359]
I was just looking at the docs page (https://rustscan.github.io/RustScan/), the first table of which seems to contain escaped HTML tags for paragraphs and images judging from the source.
I'm not sure if it's doing anything in particular visually, but it makes screenreaders do ...well ...this:
<p align="center">👩‍💻 Kali / Debian </p> column 2 <p align="center"> visited link  👩‍💻 Kali / Debian </p>

Not super pleasant to dig through :)
Would be great if this could get looked at. Thanks!

**Comment by zersiax** [comment]
ehh, Githus's getting smart with me:

Less p align="center" Greater Woman Technologist  Kali slash Debian less slashp greater column 2 less p align="center" greater visited link  Woman Technologist  Kali slash  Debian less slash p greater
The actual HTML source gets read, rather than their rendered contents :)

**Comment by lerignoux** [comment]
Hello I wanted to suggest the [following change](https://github.com/RustScan/RustScan/pull/491) to fix this issue:
Not sure if it is acceptable for you.
