### ISSUE TITLE
Current README logo is unreadable with GitHub's dark theme

### ISSUE THREAD

**Issue by mebeim** [RustScan/RustScan#364]
I though you should know that the current readme logo's text is barely readable when using the dark GitHub theme. I would have submitted a PR myself adding a white outline, but I figured you folks already have the raw project files for the logo and can do that better than me.

Screenshot:

![screenshot](https://user-images.githubusercontent.com/14198070/111413027-c40cce00-86dd-11eb-96e8-0e5a46ac9a32.png)

**Comment by bee-san** [comment]
That's a Varg problem, let me ping him :)
