### ISSUE TITLE
A large number of SYN_SENT occupies the port and cannot be released

### ISSUE THREAD

**Issue by Gu-f** [RustScan/RustScan#374]
**Describe the bug**
A large number of SYN_SENT occupies the port and cannot be released. The port is full, causing the scan to stop working, and the machine cannot communicate with other machines.

**To Reproduce**
The host system used for all tests is CentOS7.
1. Intranet environment with at least two hosts or virtual machines
2.Execute    ./rustscan -r 1-65535 -a 192.168.100.0/24 -u 100000
A few seconds later
then
rustscan stopped working
Cannot communicate with other hosts

Unexpected behavior
All hosts in segment C have port 25 open, but I only have 4 alive hosts.

**Expected behavior**

**Logs**
[~] The config file is expected to be at "/root/.rustscan.toml"
[~] Automatically increasing ulimit value to 100000.
Open 192.168.100.0:25
Open 192.168.100.1:25
Open 192.168.100.2:25
Open 192.168.100.3:25
Open 192.168.100.4:25
Open 192.168.100.5:25
Open 192.168.100.6:25
Open 192.168.100.7:25
Open 192.168.100.8:25
Open 192.168.100.9:25
Open 192.168.100.10:25
Open 192.168.100.11:25
Open 192.168.100.12:25
Open 192.168.100.13:25
Open 192.168.100.14:25
Open 192.168.100.15:25
Open 192.168.100.16:25
Open 192.168.100.189:25
Open 192.168.100.190:25
Open 192.168.100.191:25
Open 192.168.100.192:25
Open 192.168.100.193:25
Open 192.168.100.194:25
......
......
netstat -ano
All ports are used    Port cannot be released
e.g.
tcp        0      1 192.168.73.128:47916    192.168.100.122:25496   SYN_SENT    on (1.84/1/0)
tcp        0      1 192.168.73.128:59228    192.168.100.173:25502   SYN_SENT    on (0.23/0/0)
tcp        0      1 192.168.73.128:34848    192.168.100.202:25499   SYN_SENT    on (0.07/0/0)
tcp        0      1 192.168.73.128:49662    192.168.100.212:25495   SYN_SENT    on (1.83/1/0)
tcp        0      1 192.168.73.128:47678    192.168.100.104:25507   SYN_SENT    on (0.85/0/0)
......
......

**Comment by f4ct0r** [comment]
I have the same problem. And I run rustscan by using docker on mac.
