### ISSUE TITLE
There are some problems in the wiki

### ISSUE THREAD

**Issue by No-Github** [RustScan/RustScan#375]
**Describe the bug**
I refer to the content in the wiki and there are some problems in the process of using it

For example, the -p parameter is not available

**To Reproduce**
1. visit https://github.com/RustScan/RustScan/wiki/Usage
![image](https://user-images.githubusercontent.com/18167071/113279697-ff321280-9315-11eb-9fd4-5eeb967bb412.png)
2. use -p parameter
![image](https://user-images.githubusercontent.com/18167071/113279846-27ba0c80-9316-11eb-93fd-47a383c2a6a2.png)

**Expected behavior**
1. Maybe we need to update the wiki page
2. We need a more complete wiki manual

**Desktop (please complete the following information):**
 - kali 2021
 - rustscan 2.0.0

**Additional context**

The usage screenshot shown in the default readme file, the scanning syntax is
rustscan 127.0.0.1 --accessible --no-nmap --ulimit 5000
This command is also out of date, and now requires the -a parameter
![image](https://user-images.githubusercontent.com/18167071/113280597-11f91700-9317-11eb-9b19-a547b0be98c8.png)
![image](https://user-images.githubusercontent.com/18167071/113280620-1ae9e880-9317-11eb-822d-39e3dbe7d679.png)
And the --no-nmap parameter cannot be used

**Comment by skmagiik** [comment]
Wiki also shows -q and --quiet as flags. Update broke that earlier and replaced with -g or --greppable
Wiki should be updated to reflect these changes
