### ISSUE TITLE
Found Argument which wasn't expected - UPDATE THE README and Program HELP MENU

### ISSUE THREAD

**Issue by 0xtejas** [RustScan/RustScan#385]
**Describe the bug**
I downloaded the latest debian download file of rustscan from the releases, and ran `sudo dpkg -i <file.deb>` 

**To Reproduce**
1. Download the Rust Scan from releases `Fixing Cargo Lock`.
2. In kali linux 2020.1
3. Run `sudo dpkg -i <file.deb>`, it gets installed.
4. try running rustscan with the command given in the help `rustscan -T 1500 127.0.0.1 -- -A -sC `.
5. You will get error as `error: Found argument 'google.com' which wasn't expected, or isn't valid in this context`

**Expected behavior**
It has to run the scan and show output.

**Screenshots**
![image](https://user-images.githubusercontent.com/47889755/118433535-da90cf00-b6f8-11eb-9036-87243769daae.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Browser: Chrome, FireFox

**Comment by joeftiger** [comment]
I noticed as well that it's using `-T` instead of the lowercase `-t`. The example needs to be updated in the code.

**Comment by tejas15802** [comment]
> I noticed as well that it's using `-T` instead of the lowercase `-t`. The example needs to be updated in the code.

I don't think so, upon doing it I get 
![image](https://user-images.githubusercontent.com/47889755/119076962-19809680-ba11-11eb-88c1-6438e02d89fc.png)

**Comment by joeftiger** [comment]
> > I noticed as well that it's using `-T` instead of the lowercase `-t`. The example needs to be updated in the code.
> 
> I don't think so, upon doing it I get
> ![image](https://user-images.githubusercontent.com/47889755/119076962-19809680-ba11-11eb-88c1-6438e02d89fc.png)

You need `-a` in front of your address as well.

**Comment by tejas15802** [comment]
> > > I noticed as well that it's using `-T` instead of the lowercase `-t`. The example needs to be updated in the code.
> > 
> > 
> > I don't think so, upon doing it I get
> > ![image](https://user-images.githubusercontent.com/47889755/119076962-19809680-ba11-11eb-88c1-6438e02d89fc.png)
> 
> You need `-a` in front of your address as well.

Okay that seems to work, then documentation has to bee updated and the program's example also

**Comment by blackcodersec** [comment]
still this issue here.

**Comment by 0xtejas** [comment]
IDK if this is fixed. I feel like nobody cares. I'm closing this.
