### ISSUE TITLE
When I scan a file, the command line doesn't scan, it stays where it is

### ISSUE THREAD

**Issue by F1ady** [RustScan/RustScan#388]
Hello, I ran into a problem when running
My VPS is from Ubuntu 20
When I scan a file, the command line doesn't scan, it stays where it is
Is there any problem with my settings, I didn't find any profiles in the root directory
![image](https://user-images.githubusercontent.com/55682884/120106228-dea7fc80-c18e-11eb-9e77-ab6a149173aa.png)

**Comment by starnightcyber** [comment]
Yes, it gets stuck ~

**Comment by alonek1** [comment]
Same problem here.
not also from loading file, but doesn't scan anywhere. It was working but now it doesn't.

**Comment by lovelyjuice** [comment]
+1
