### ISSUE TITLE
Rustscan is the best port scanning tool I've ever seen, but it's also the tool with the most junk and stupid documents I've ever seen in GitHub. I didn't know how to use scripts custom after reading it for a long time

### ISSUE THREAD

**Issue by k0njac** [RustScan/RustScan#390]
Rustscan is the best port scanning tool I've ever seen, but it's also the tool with the most junk and stupid documents I've ever seen in GitHub. I didn't know how to use scripts custom after reading it for a long time

**Comment by starnightcyber** [comment]
From help doc, we do not know the args we shall input to get what we want ~
