### ISSUE TITLE
thread 'main' panicked at 'Too many open files. Please reduce batch size.'

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#40]
Did you just see this error?

Try this guide:
[https://github.com/brandonskerritt/RustScan/blob/master/README.md#-thread-paniced-at-main-too-many-open-files](https://github.com/brandonskerritt/RustScan/blob/master/README.md#-thread-paniced-at-main-too-many-open-files)

**Comment by bernardoamc** [comment]
Closing this one since we have a wiki now. :)
