### ISSUE TITLE
-oN file.txt doesn't work

### ISSUE THREAD

**Issue by ludoboulanger** [RustScan/RustScan#400]
**Describe the bug**
Hi all, it might just be me that doesn't know how to use the tool properly, but I am trying to run `rustscan [IP] -- -A -oN file.txt` but keep getting the error

```
Failed to open normal output file file.txt for writing
QUITTING!
```

I went through the issues and didn't see it meaning it probably just is me who is missing something?

**To Reproduce**
1. Run the command in the description

**Expected behavior**
The tool should be able to open the file and output the script results to it

**Screenshots**

**Desktop (please complete the following information):**
- Rustscan Version: `1.10.0` pulled from `docker`
 - OS: Kali running on V box
 - Version: 2021.2

Anyway, thanks for the help :)

**Comment by wa7sa34cx** [comment]
There is 2.0.0 version already. Try it! Maybe your problem solved already...

**Comment by ludoboulanger** [comment]
> There is 2.0.0 version already. Try it! Maybe your problem solved already...

Yeah I tried it, unfortunately had no luck with it either

**Comment by wa7sa34cx** [comment]
Check write permissions for file.txt 🧐
