### ISSUE TITLE
Scanning through proxies

### ISSUE THREAD

**Issue by Karmaz95** [RustScan/RustScan#407]
It would be very nice if you add SOCKS5 proxy support.

For example:
```
rustscan --proxies <comma separated list of proxies> <target>
rustscan --proxies socks5://127.0.0.1:9050 scanme.nmap.org
```
or
```
rustscan --proxies <proxy_new_line_list> <target>
rustscan --proxies sox.txt scanme.nmap.org

content of sox.txt
socks5://127.0.0.1:9050
socks5://127.0.0.1:9051
socks5://127.0.0.1:9052
socks5://127.0.0.1:9053
```

**Comment by albertlarsan68** [comment]
Would also be nice if it could also support HTTP proxies

**Comment by muelli** [comment]
> Whats the benefit of using this proxy feature instead of setting up all your proxying/tor/vpn to get to your anon machine then installing rustscan there (or any other "networking" tools)?

Sometimes it's difficult to install rustscan on another machine. Running a proxy might be more feasible.

**Comment by ceylanb** [comment]
@bee-san why did you close this issue as completed? Was this feature implemented somehow? If so, I couldn't find anything about it in this repo.

**Comment by bee-san** [comment]
Backlog bankruptcy was declared
https://www.productplan.com/blog/backlog-bankruptcy/
