### ISSUE TITLE
Build fails on Apple Monterey with MacPorts

### ISSUE THREAD

**Issue by Take-A-Breath** [RustScan/RustScan#410]
**Describe the bug**
After migrating to a MacBook Pro running Monterey from one running Big Sur, where the application worked fine, the build fails:

**To Reproduce**
`sudo port install rustscan`

Error received:
`Error: Failed to build rustscan: command execution failed`

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Apple M1 processor
 - MacPorts 2.7.1

**Additional context**
[main.log](https://github.com/RustScan/RustScan/files/7447362/main.log)

**Comment by jak010** [comment]
i also same problem and in my case installed use with `cargo` 
```
$ brew install cargo
...
$ brew install rustscan
...
$ ln -s ~/.cargo/bin/rustcan /usr/local/bin/rustscan
```
Will there be any problems if I install it in the same way as above?
