### ISSUE TITLE
thread 'main' panicked at 'Too many open files.

### ISSUE THREAD

**Issue by tesqie** [RustScan/RustScan#417]
**Describe the bug**
`] File limit higher than batch size. Can increase speed by increasing batch size '-b 1048476'.
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/scanner/mod.rs:132:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`
When Running:
`rustscan 192.168.1.0/24 -t 500 -b 1500 -- -A 10.10.10.74`
Using Docker

**To Reproduce**
Just use the command I typed in

**Expected behavior**
Rust scan running normally

**Screenshots**
![image](https://user-images.githubusercontent.com/23288409/145598968-09fb86b1-b93d-4116-95ab-e14dee53b310.png)

**Desktop (please complete the following information):**
Linux kali 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux

**Comment by ctf-adam** [comment]
Running into the same error message:
> $ rustscan -b 2500 -a target.thm -- -A -sC
Automatically increasing ulimit value to 1000.
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/scanner/mod.rs:138:29
stack backtrace:
   0:     0x555b6a8944ba - <unknown>
   1:     0x555b6a7691cc - <unknown>
   2:     0x555b6a893c26 - <unknown>
   3:     0x555b6a89361a - <unknown>
   4:     0x555b6a892ee7 - <unknown>
   5:     0x555b6a882133 - <unknown>
   6:     0x555b6a88210c - <unknown>
   7:     0x555b6a8820ea - <unknown>
   8:     0x555b6a86892f - <unknown>
   9:     0x555b6a86a721 - <unknown>
  10:     0x555b6a87a066 - <unknown>
  11:     0x555b6a8820c3 - <unknown>
  12:     0x555b6a871e05 - <unknown>
  13:     0x7f1116b0118a - <unknown>
  14:     0x7f1116b01245 - <unknown>
  15:     0x555b6a6d90aa - <unknown>
  16:                0x0 - <unknown>
zsh: IOT instruction  rustscan -b 2500 -a target.thm -- -A -sC
                                                                                                                   
$ uname -a                  
Linux <redacted> 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux

**Comment by ctf-adam** [comment]
Fixed it - the problem was probably `~/.rustscan.toml` - I updated:

* `batch_size = 2000` (from `1000`)
* `ulimit = 5000` (from `1000`)
