### ISSUE TITLE
mac m1 系统无法下载

### ISSUE THREAD

**Issue by linuxdy** [RustScan/RustScan#421]
![image](https://user-images.githubusercontent.com/50064309/147442716-a2096bdf-b5f4-4f56-ab05-49c0bc316038.png)

Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: rustscan: no bottle available!
You can try to install from source with:
  brew install --build-from-source rustscan
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**Comment by jak010** [comment]
in my case..

https://github.com/RustScan/RustScan/issues/410#issuecomment-1030573200
