### ISSUE TITLE
error argument -a 

### ISSUE THREAD

**Issue by D0N-B0T** [RustScan/RustScan#423]
![image](https://user-images.githubusercontent.com/13562845/147510631-2408770e-849d-4017-9851-44cf6ad13f29.png)

**Comment by xrzhev** [comment]
The -a option **is not present** in "rustscan 1.10.0".
If you run it without the -a option, it will work.
`docker run -it --rm --name rustscan rustscan/rustscan:1.10.0 google.com`

**Comment by wellencamass** [comment]
update the readme then?
