### ISSUE TITLE
[Feature Request] make the range -r  do  ----->  1-79, 81-442,444-8079,8081-65535

### ISSUE THREAD

**Issue by gprime31** [RustScan/RustScan#424]
[Feature Request] make the range -r  do  ----->  1-79, 81-442,444-8079,8081-65535  exclude 80,443,8080 but scan the rest.
so I can do multiple ranges, or make a flag to exclude unwanted ports in a range. whatever is easier.
unless there is another way to do this I might have missed.
Thanks.
Great tool!!

**Comment by Autumn-27** [comment]
May I ask if the range parameter can support 1-6, 11200-300
