### ISSUE TITLE
Target IP file more simple

### ISSUE THREAD

**Issue by abrekhov** [RustScan/RustScan#428]
**Describe the solution you'd like**
It will be fantastic if you can make flag for simple hostlist.

**Describe alternatives you've considered**

TOML file is not very simple to use, e.g.:
adresses = ["ip1","ip2",...]

If I have many of them better to do have separate file like 
ip1
ip2
ip3
...

**Comment by kgnfth** [comment]
how about this [Hosts file as input](https://github.com/RustScan/RustScan/wiki/Things-you-may-want-to-do-with-RustScan-but-don't-understand-how#hosts-file-as-input)

**Comment by abrekhov** [comment]
@kgnfth that is great. I'm blind. Thanks!
