### ISSUE TITLE
Rustscan in only scanning ipv6?

### ISSUE THREAD

**Issue by rew1nter** [RustScan/RustScan#432]
Does rustscan only scan ipv6 now?

**Screenshot: 
![IMG_20220404_092306](https://user-images.githubusercontent.com/64508791/161469070-61165462-b7d6-4343-bb10-88487d4f8820.jpg)

**Comment by Jaxii** [comment]
Google is increasingly utilizing IPv6 over IPv4 is all that means. 

(https://www.google.com/intl/en/ipv6/statistics.html)
