### ISSUE TITLE
[feature request] abilty to specify config file 

### ISSUE THREAD

**Issue by cocoonkid** [RustScan/RustScan#437]
This might be stupid but I can't find a flag for that in the docs.

But it would be great to have:

`rustscan -f target.toml -a hosts.txt`  for example

Thanks!

**Comment by cph-w** [comment]
Hello @cocoonkid, I've implemented this feature on a branch and opened a pull request because I would also like this feature. Love this tool but as someone who likes to avoid home directory clutter I would also love to see this feature in :)

**Comment by cocoonkid** [comment]
@cph-w you're the man!!  really really nice.

Looking forward to the PR getting approved.

@bee-san Please master of bees have a look thru your five-eyes :-)

**Comment by khayyamsaleem** [comment]
I think this can be closed, right?

**Comment by bee-san** [comment]
Yes it can! Thanks so much for tagging me :)
