### ISSUE TITLE
Current release has not up to date Cargo.lock file

### ISSUE THREAD

**Issue by guddaff** [RustScan/RustScan#440]
Current release has not up to date Cargo.lock file.

when running:

```
cargo build --release --locked  
```

cargo throws the following error.

```
error: the lock file /home/guddaff/Downloads/RustScan-2.1.0/Cargo.lock needs to be updated but --locked was passed to prevent this
```

**Comment by bee-san** [comment]
thanks a lot!!

**Comment by LeoFVO** [comment]
This issues have been fixed, I tried to reproduce but there isn't the issue anymore.
Maybe you can close this ;)
