### ISSUE TITLE
.deb file in 2.1.0 Release

### ISSUE THREAD

**Issue by geordanex** [RustScan/RustScan#441]
**Please include .deb file to debian base systems**
I would appreciate it if you could put the .deb file in the release assets.

keep up the good work!

**Comment by daniejstriata** [comment]
The .deb files for 2.1.0 was not included in the release.

**Comment by oscarholst** [comment]
I also noticed it's missing from the release, worked perfectly for me to run the provided "rustscan-debbuilder" tool inside the repo though. :-) For convenience i have attached the compiled deb package for 2.1.0 for both i386 and amd64 if you do not wish to compile the deb yourself.
[rustscan_2.1.0_both.zip](https://github.com/RustScan/RustScan/files/9473239/rustscan_2.1.0_both.zip)
