### ISSUE TITLE
RustScan is considerably slower when using a "host" file rather than CIDR notation for essentially the same number of hosts

### ISSUE THREAD

**Issue by t3chn0t3s** [RustScan/RustScan#442]
Greetings,

I'd like to start by stating how amazed I've been with RustScan.  It is jaw dropping fast!  I recently installed it on Kali 2022.1 using the rustscan_2.0.1_amd64.deb file.

I found that if I scan using the '-a 172.25.170.0/24 -p22,80.443,445 -g' arguments it takes about 6 seconds to scan the 254 hosts.
![image](https://user-images.githubusercontent.com/46801776/169206365-e5b79177-602a-40b2-bb16-e3ed002cb562.png)

I'm trying to comply to my scope as much as possible and know that 172.25.170.1 is out of scope.  Since I am unaware of a way to instruct RustScan to only scan 172.25.170.2 - 172.25.170.254 I used the following nmap "command" to generate a host file, named scope.txt

```
nmap -sL -n 172.25.170.2-254 | awk '/Nmap scan report/{print $NF}' | tee scope.txt
```
I then used the '-a 'scope.txt' -p22,80,443,445 -g' arguments to scan.  Unfortunately, this takes considerably longer to scan.  For example, my most recent "test" scan took about 13 minutes to complete.

![image](https://user-images.githubusercontent.com/46801776/169211245-2829ebcc-bb37-4993-950c-b60bc1d19492.png)

I did also try the '-a 172.25.170.2-254' argument but since I didn't see that format used in the documentation I canceled it about 5 minutes into the scan.  I'm not sure that format was valid, but assuming that it was 5 minutes is still considerably longer than the 6 seconds it takes when using the CIDR notation (/24).

Finally, as a sanity check I did check the line count of my scope.txt file and confirmed its about 253 hosts/lines.
![image](https://user-images.githubusercontent.com/46801776/169209716-4f13d5ff-19e2-442d-b85a-78ddab998891.png)

Thank you all for such a great tool.  I look forward to using it regularly.

**Comment by PsypherPunk** [comment]
@t3chn0t3s, could you re-test this on a recent version?

Both the CIDR and input-file variants appear to run in about the same time.

**Comment by PsypherPunk** [comment]
@t3chn0t3s, I'm going to assume this is no longer an issue and close this.

If you're still finding otherwise, please feel free to re-open.
