### ISSUE TITLE
Hash Table Overflow

### ISSUE THREAD

**Issue by ghost** [RustScan/RustScan#447]
**Describe the bug**
Rustscan crashes with a hash table overflow

**To Reproduce**
Run: rustscan -a 10.0.0.0/8 --top

**Expected behavior**
It works

**Console Output**
```
Automatically increasing ulimit value to 1000.
thread 'main' panicked at 'Hash table capacity overflow', /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.0/src/raw/mod.rs:96:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      rustscan -a 10.0.0.0/8 --top
```
**Desktop (please complete the following information):**
 - OS: Kali Linux ARM64
 - Version rustscan 2.1.0
 - Device: Raspberry Pi 4

**Additional context**
Compiled for Arm64 from latest release

**Comment by jabbate19** [comment]
So I tried to run this to replicate. This is trying to scan 16777216 IPs, which would require 858 GB of memory allocation. This is simply a limit on memory as far as I can tell, I do not think there is much that can be done?
