### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MyrickCapital** [RustScan/RustScan#450]
By far the stupidest documentation I've ever read on Git. I'm having to thoroughly read through so much extra nonsense and fluff to find the information I'm looking for. yawn.

**Comment by Owletti** [comment]
@MyrickCapital Maybe you should rewrite it! It would be incredibly helpful to other users of the software, and you'd be contributing to an open-source project. Sounds like a pretty great opportunity to get involved!

**Comment by bee-san** [comment]
@MyrickCapital has not made a PR to rewrite the documentation in the 2 years since this issue, so it can't have been that "stupid" 😜 

Closing ticket.

**Comment by MyrickCapital** [comment]
I look at you and just feel sorry.
