### ISSUE TITLE
[!] Error Exit code = 11- Nmap results fail to load results

### ISSUE THREAD

**Issue by cybertuxh4xor** [RustScan/RustScan#454]
** Nmap results fail to load**
rustscan 2.1.0 and version 2.0

![image](https://user-images.githubusercontent.com/88122300/189494827-59c7d22f-39cd-43de-b6f6-b550793c047d.png)
![image](https://user-images.githubusercontent.com/88122300/189494838-ac5efeef-32b1-4d5b-884b-6afb64f2710b.png)

**Comment by namteckor** [comment]
Also observing this error running rustscan 2.0.0 on Kali Linux 2022.3
![rustscan_nmap_error_exit_code_11](https://user-images.githubusercontent.com/98191269/189833335-adf8d26e-1c13-413d-9a35-88ca97b05be6.png)

**Comment by zevelix** [comment]
I'm new so I may not be correct on all points but I was having the same issue with rustscan 2.1.0 on Kali 2022.3. I'm pretty sure this is an issue with nmap(specifically the scripting engine?), not rustscan. Exit code 11 is a segmentation fault and when I tried to just use 'nmap -sV -sC {ip}' (v 7.92) it seemed to finish up but the last line was 'zsh: segmentation fault.' After some searching I found this [issue](https://github.com/nmap/nmap/issues/2518) where some folks suggested trying nmap v7.93. After downloading and compiling I am no longer getting a seg fault. Though it does seem to be having an issue with a few of the scripts.
```
NSE: Failed to load '/usr/local/bin/../share/nmap/scripts/http-favicon.nse'.
NSE: Failed to load '/usr/local/bin/../share/nmap/scripts/iscsi-info.nse'.
NSE: Failed to load '/usr/local/bin/../share/nmap/scripts/mongodb-databases.nse'.
NSE: Failed to load '/usr/local/bin/../share/nmap/scripts/mongodb-info.nse'.
NSE: Failed to load '/usr/local/bin/../share/nmap/scripts/sip-methods.nse'.
NSE: Failed to load '/usr/local/bin/../share/nmap/scripts/ssh-hostkey.nse'.
```

**Comment by namteckor** [comment]
Thanks @zevelix! - I tried with the compiled nmap v7.93 and so far have not seen the Error Exit Code = 11 segmentation fault again

**Comment by dmiller-nmap** [comment]
This is a result of https://github.com/nmap/nmap/issues/2482, which has been fixed in development.
