### ISSUE TITLE
Lockfile out of sync with releases

### ISSUE THREAD

**Issue by grawlinson** [RustScan/RustScan#460]
**Is your feature request related to a problem? Please describe.**

`Cargo.lock` does not seem to be updated in-sync with new versions. I've had to patch the last two lockfiles before packaging the project for Arch Linux.

**Describe the solution you'd like**

For the lockfile to be updated in-sync with every release. I think this can be done via `cargo update` or `cargo generate-lockfile`.

**Comment by bee-san** [comment]
This is sad to hear, but thanks for pointing it out! I knew I forgot something....

Maybe I'll write a release script to run that just runs the right commands 😅

**Comment by bee-san** [comment]
Wrote a release script and updated lock file :)
