### ISSUE TITLE
Append result of Nmap to ouput file instead of overwriting.

### ISSUE THREAD

**Issue by zoli4c** [RustScan/RustScan#461]
I just tried to run Rustscan to scan multiple host as 1 line cmd like:
 `rustscan -a 192.168.136.172,192.168.136.173 -- -A -sV -Pn -oG /tmp/output.txt` .

Also, I need to grep content from `/tmp/output.txt` for 2 hosts above. But It seems Rustscan push the output of Nmap sequencely and the last result will be overwrited to previous. (just obtain result only one of these two hosts).

```bash
zoli4c$ cat /tmp/output.txt 
# Nmap 7.80 scan initiated Wed Nov  9 17:30:34 2022 as: nmap -vvv -p 80,443 -A -sV -Pn -oG tmp/test 192.168.136.172
# Ports scanned: TCP(2;80,443) UDP(0;) SCTP(0;) PROTOCOLS(0;)
Host: 192.168.136.172 ()        Status: Up
Host: 192.168.136.172 ()        Ports: 80/open/tcp//http//Microsoft IIS httpd 10.0/, 443/open/tcp//https?///
# Nmap done at Wed Nov  9 17:32:17 2022 -- 1 IP address (1 host up) scanned in 103.26 seconds
```

So, can you modify that feature that will append the Nmap's result instead of overwriting?
Thank you,
@zoli4c

**Comment by HydroSausager** [comment]
use -oX \{\{ip\}\}.xml , it works

**Comment by SySx-Dragonfire** [comment]
> use -oX \{\{ip\}\}.xml , it works

With the outdated [nmap_Merger](https://github.com/CBHue/nMap_Merger) it is possible to Merge the files. And also to directly generate a html, if xsltproc is installed.
