### ISSUE TITLE
Transition from structopt to clap

### ISSUE THREAD

**Issue by Paliaq** [RustScan/RustScan#466]
Hey everyone,

I've been very impressed with this project and its improvements over nmap, and I have been looking for a way to help with the project.

I noticed structopt is used rather than clap, which is unnecessary since clap v3 as most of structopts functionality has been integrated into the clap project, leaving structopt in a state of maintenance.

So I'm just wondering if there's a reason for this (e.g. performance, compilation time), and would like to gauge the interest in making this transition to clap if there is any.

**Comment by bee-san** [comment]
No reason! 👏🏻  We just use StructOpts because Clap v3 wasn't a thing back in the day 🧓🏻 

I use Clap v3 in one of my other projects [ares](https://github.com/bee-san/Ares), so it'd be nice to use the same CLI arg-parsing lib throughout :)
