### ISSUE TITLE
Only ethernet devices can be used for raw scans on Windows

### ISSUE THREAD

**Issue by ket000** [RustScan/RustScan#467]
when running the ruststan -a ip_address on windows, getting belo.

[~] Starting Script(s)
Error in OpenService
Only ethernet devices can be used for raw scans on Windows. Use
the --unprivileged option for this scan.
QUITTING!
[!] Error Exit code = 1

Trying to use  --unprivileged does not work

**Comment by VKECE** [comment]
thank you
