### ISSUE TITLE
Request: How to scan a list of IP from a txt file

### ISSUE THREAD

**Issue by Moskitoz** [RustScan/RustScan#487]
Can you provide for us the valid cmd how to scan a list of IP's from a txt file?

**Comment by PsypherPunk** [comment]
Is this covered by the [*Hosts file as input*](https://github.com/RustScan/RustScan/wiki/Things-you-may-want-to-do-with-RustScan-but-don't-understand-how#hosts-file-as-input) section of the wiki?
