### ISSUE TITLE
Release RustScan as a library as well

### ISSUE THREAD

**Issue by joojscript** [RustScan/RustScan#497]
**Is your feature request related to a problem? Please describe.**
I would love to integrate RustScan inside a Rust application, but currently, the only way to do it is actually installing it on the OS with `cargo install`, and then, calling it by the shell of the system, which is not optimal.

**Describe the solution you'd like**
It would be really great to just add a `lib` entry point in `Cargo.toml` (at least), and release it, so rust developers could embed it into open-source solutions.

**Describe alternatives you've considered**
- Add `lib` entry to `Cargo.toml`;
- Modularize such that RustScan can be used as a library as well;

**Additional context**
N/a

**Comment by StefanoSetti** [comment]
Are you willing to implement it?

**Comment by bee-san** [comment]
I will take any PR that implements RustScan as a library :)
