### ISSUE TITLE
Include original hostname as an additional script field, alongside the resolved IP address

### ISSUE THREAD

**Issue by LukeDSchenk** [RustScan/RustScan#501]
**Is your feature request related to a problem? Please describe.**

When I use Nmap on a hostname and it gets resolved, the scan report is shown as being for `<hostname> (<resolved_ip>)` as follows:
![image](https://user-images.githubusercontent.com/41804945/217711690-49c06986-5bd1-4c49-90fb-52dd614768c1.png)

But when I use Rustscan on a hostname and it gets resolved, the report output only shows the IP address of the domain:
![image](https://user-images.githubusercontent.com/41804945/217713608-94625de7-61ab-4705-88ca-18972fa1d2ed.png)

The same applies to running custom scripts too. The original hostname associated with the IP address is not accessible via the custom script arguments.

**Describe the solution you'd like**

I would like to be able to write custom scripts with an additional parameter called "hostname" or something like that, so that when running rustscan against multiple hostnames I can have the hostname which was resolved accessible in my scripts. You know, something like: 

```python
#call_format = "python3 {{script}} {{ip}} {{hostname}} {{port}}"
```
And if the IP was not resolved from a hostname, then maybe hostname can just be the IP address instead, or something like that.

**Additional context**

I would love to build this feature myself, but I thought it would be good to ask for some guidance here to make sure that I am going about it in the best and most seamless way. Any guidance from the rustscan core team would be greatly appreciated, but regardless I will happily hack away at this. 

Thank you for making such a useful tool, and I look forward to hearing from you!

**Comment by Ghs0my** [comment]
When my target is the domain name, it needs to display the domain:port. The current result is IP:POR. You know, in some scenarios, simply using IP:PORT is not useful. It must be domain:port
