### ISSUE TITLE
Installation Guide suggests downloading .deb from "releases" but new releases don't have a .deb file

### ISSUE THREAD

**Issue by Crypto-Cat** [RustScan/RustScan#504]
**Describe the bug**
https://github.com/RustScan/RustScan/wiki/Installation-Guide#%EF%B8%8F-debian--kali suggests to download .deb package and install with `sudo dpkg -i` but checking through the releases, the last one to contain a .deb file was 2020.

**To Reproduce**
1. Go to "releases"
2. Look for .deb package

**Expected behavior**
Find .deb package

**Comment by 2xfree** [comment]
You can build your own .deb file. Clone the repo, go into the `rustscan-debbuilder` repository, make sure `docker-compose` is installed and run `run.sh`. This will build the .deb file and place it into `rustscan-debbuilder/debs/` then you can just install the .deb file like normal.

**Comment by Tropical-Smootie** [comment]
> You can build your own .deb file. Clone the repo, go into the `rustscan-debbuilder` folder, make sure `docker-compose` is installed and run `run.sh`. This will build the .deb file and place it into `rustscan-debbuilder/debs/` then you can just install the .deb file like normal.

thank you this was very informative.

**Comment by noob0x01** [comment]
Hey  @2xfree @Tropical-Smootie 

Hey,
Kindly share the full please (include command)

Thanks

**Comment by sanjay493** [comment]
The details of command as follow:
` sudo apt update  `
`sudo apt install -y docker.io`
`sudo systemctl enable docker --now`
`sudo git clone https://github.com/RustScan/RustScan.git`
`cd RustScan `
`cd rustscan-debbuilder`
`sudo ./run.sh`

it will create rustscan_2.1.1_amd64.deb inside rustscan-debbuilder/debs/ folder
`cd debs`
`sudo dpkg -i rustscan_2.1.1_amd64.deb` // to install rustscan on kali

`rustscan -h` // to check rustscan version

**Comment by bee-san** [comment]
Sadly it's not in the CI so it's hard to add manually to releases :( 

Feel free to add a .deb builder to https://github.com/RustScan/RustScan/blob/master/.github/workflows/release.yml to add it
