### ISSUE TITLE
Docker version does not allow file input

### ISSUE THREAD

**Issue by Bozx** [RustScan/RustScan#506]
docker run -it --rm --name rustscan rustscan/rustscan:2.0.0 -q --scan-order "Random" -a hosts.txt gives error : 
[~] The config file is expected to be at "/home/rustscan/.rustscan.toml"
[!] Host "./nadeo/hosts.txt" could not be resolved.
[!] No IPs could be resolved, aborting scan.
Regards.

**Comment by pnhb112345** [comment]
any solution for this?

**Comment by blacksper** [comment]
same issue

**Comment by st33lface** [comment]
Yo should mount a volume in your container to be able to run it. Docker containers can't read your filesystem. 

Eg: docker run -it --rm -v $(pwd):/hosts.txt --name rustscan rustscan/rustscan:2.0.0 -q --scan-order "Random" -a hosts.txt
