### ISSUE TITLE
File output

### ISSUE THREAD

**Issue by Bozx** [RustScan/RustScan#507]
Needs a file output for scans
Would be awesome.
Regards.

**Comment by RFHACKE** [comment]
yeah a output option that outputs only the result of rustscan in [IP]:[PORT] format into a file without any kind of nmap scanning

**Comment by RFHACKE** [comment]
i wrote a  script for rustscan that prints output into a file in IP:PORT format.Place the script into the ~/rustscan_scripts folder then 
run rustscan with the --scripts custom argument.also save the example.txt file as a python file and then place into the specified folder.
[example.txt](https://github.com/RustScan/RustScan/files/11982632/example.txt)
the output will be in a file with name IP.txt
