### ISSUE TITLE
RustScan scripts parser error

### ISSUE THREAD

**Issue by qwrdxer** [RustScan/RustScan#527]
**Describe the bug**

scripts\mod.rs  ,  line 236
        let arguments = shell_words::split(&to_run).expect("Failed to parse script arguments");

my` to_run` variable like:
python3 C:\\Users\\qwrdxer\\.rustscan_scripts\\test_script.py 192.22.105.149 22,111,25,110,3344,8080,8888

after call the func  ` shell_words::split(&to_run)`
![image](https://github.com/RustScan/RustScan/assets/46155167/3b272690-0c35-4e97-a29c-c5c818ba22ce)
the  '\\' was delete !  I don't know more about this lib , here  is my environment:

os: windows10 
ide: Clion

The temporary solution is
change 
`let arguments = shell_words::split(&to_run).expect("Failed to parse script arguments");`
to
`let arguments:Vec<String> =to_run.split_whitespace().map(|s| s.to_string()).collect();`

**screen shot**

![image](https://github.com/RustScan/RustScan/assets/46155167/639701cb-5645-4087-8630-401eb429ef47)
![image](https://github.com/RustScan/RustScan/assets/46155167/b1bf8165-401f-47c0-9ca8-e6894e6bb07f)

**Comment by bee-san** [comment]
hi, we declared issue bankrupcty in april.

reopening this as this still exists

**Comment by PsypherPunk** [comment]
@qwrdxer, can you confirm if you're still seeing this in the current version?
