### ISSUE TITLE
The --no-nmap option does not work

### ISSUE THREAD

**Issue by eiko4** [RustScan/RustScan#529]
The --no-nmap option does not work

example: `rustscan --no-nmap -a hackerone.com`

**Comment by Tripse** [comment]
please use -g

**Comment by Tripse** [comment]
> The --no-nmap option does not work
> 
> example: `rustscan --no-nmap -a hackerone.com`

please use -g

**Comment by bugoverfl0w** [comment]
> > The --no-nmap option does not work
> > example: `rustscan --no-nmap -a hackerone.com`
> 
> please use -g

This option still runs nmap in background, you just hide nmap output, not stop nmap feature :)
