### ISSUE TITLE
rustscan-2.2.2-x86_64-linux.tar.xz still contains the old version

### ISSUE THREAD

**Issue by leorac** [RustScan/RustScan#576]
Hello
the binary package of this release still contains the old version.

**Comment by popey** [comment]
I built it from source, and indeed it still reports the previous version number.

**Comment by leorac** [comment]
That's probably only a banner problem?

**Comment by popey** [comment]
```
 alan@Alans-MacBook-Pro  ~/Personal/RustScan/RustScan  ◈ 2.2.2  git status
HEAD detached at 2.2.2
nothing to commit, working tree clean
 alan@Alans-MacBook-Pro  ~/Personal/RustScan/RustScan  ◈ 2.2.2  cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
 alan@Alans-MacBook-Pro  ~/Personal/RustScan/RustScan  ◈ 2.2.2  ./target/debug/rustscan --version
rustscan 2.1.1
 alan@Alans-MacBook-Pro  ~/Personal/RustScan/RustScan  ◈ 2.2.2 
```

**Comment by popey** [comment]
So yeah, it just looks like the `./Cargo.toml` hasn't been udpated.

**Comment by bee-san** [comment]
https://github.com/RustScan/RustScan/pull/577

ah cargo lock too. probably some other places also...

i cut my fingers quite badly accidentally yesterday, so i'll have to look at this later this week sadly unlwss someoen else wants to look at it :)

**Comment by popey** [comment]
No rush, take your time. Thanks for the quick response on the issue ❤️

**Comment by tyloren0a** [comment]
same [rustscan_2.2.2_amd64.deb](https://github.com/RustScan/RustScan/releases/download/2.2.2/rustscan_2.2.2_amd64.deb) debian version. wrong version number

**Comment by bee-san** [comment]
yes all versions will be wrong until i PR a cargo update 😂
