### ISSUE TITLE
Build fails on RPI

### ISSUE THREAD

**Issue by brandonskerritt** [RustScan/RustScan#58]
I have a docker file which builds RustScan on RPI (as well as normal Debian).

Normal Debian succeeds.

To recreate, run this file:
https://github.com/brandonskerritt/RustScan/blob/master/rustscan-debbuilder/run.sh

Something about maths with U64 and U32 not possible.

**Comment by brandonskerritt** [comment]
```
135 |             println!("Your file description limit is higher than the batch size. You can potentially increase the speed by increasing the batch size, but this may cause harm to sensitive servers. Your limit is {}, try batch size {}.", x, x - one);
    |                                                                                                                                                                                                                                                   ^^^ expected `u32`, found `u64`
```

This might be solved by my push to master in a few seconds

**Comment by brandonskerritt** [comment]
This is still broken :(

**Comment by brandonskerritt** [comment]
I think this is caused by us using U64, whereas I386 and Arm64 need u32.

Specifically, the rlimit function returns u64. 

@bernardoamc do you mind taking a look at this?

You can confirm if it is working or not by running the docker script. In the `rustscan-debbuilder` folder run `./run.sh` which will run 3 docker containers to build for the 3 Debian systems, 
* Amd64
* Arm64
* i386
And then place them into a folder, `debs`, as a sub-directory of `rustscan-debbuilder` :)

**Comment by bernardoamc** [comment]
I'm going to replace our `u64` for `u32` everywhere, we don't need to deal with any values higher than `u32` :)
