### ISSUE TITLE
New releases are not in docker hub

### ISSUE THREAD

**Issue by fakeNews-jpg** [RustScan/RustScan#584]
**Describe the bug**
Releases 2.2.2 and 2.2.3 are not in https://hub.docker.com/r/rustscan/rustscan/tags 

**To Reproduce**
1. Go to ['docker hub'](https://hub.docker.com/r/rustscan/rustscan/tags)
2. See last tag

**Expected behavior**
Releases 2.2.2 and 2.2.3 should be available

**Comment by bee-san** [comment]
Known issue, CI is failing.
https://github.com/RustScan/RustScan/actions/runs/8910878823

https://github.com/RustScan/RustScan/pull/570
