### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./rustscan)

### ISSUE THREAD

**Issue by winezer0** [RustScan/RustScan#586]
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./rustscan)

my system is GLIBC_2.17 

Can you provide the version with the best compatibility

**Comment by bee-san** [comment]
Found these comments related to this :) 
https://github.com/rust-lang/docker-rust/issues/77#issuecomment-1335549749

OR we can use Cross to compile it https://github.com/cross-rs/cross 

If you can @winezer0 would be easier to update your GLIBC or use the Docker image. This would be the easiest way to fix it right now 🤔

**Comment by winezer0** [comment]
Okay, thank you.
