### ISSUE TITLE
Publish to Homebrew Core

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#59]
Homebrew core is the core Homebrew formulae.

Instead of the 2 step approach we currently have for homebrew, if we publish to core, we can change it to `brew install rustscan`

Another pentesting tool, Pwncat, is in Homebrew core with 400 stars. This means that, Rustscan, with 700 stars, should be able to make it into Homebrew core.

To do this, we will need to re-create the Homebrew file and submit it as a pull request to Core. The current file can be found here:
https://github.com/brandonskerritt/homebrew-rustscan/blob/master/Formula/rustscan.rb
Pwncat's Homebrew core file looks like:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/pwncat.rb

It would be a good idea to take inspiration from Pwncat, as I have found the Homebrew documentation to be confusing.

The documentation for Homebrew core is here:
https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-add-a-new-formula-for-foo-version-234-from-url.

I am looking for some help to do this, as I am not a Mac user. If anyone wants to help out, you will be added to the README along with all the other contributors :D 

# Links
https://github.com/Homebrew/homebrew-core

**Comment by brandonskerritt** [comment]
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by brandonskerritt** [comment]
https://github.com/marketplace/actions/bump-homebrew-formula

**Comment by bernardoamc** [comment]
Can we close this one? 😁

**Comment by smackhack** [comment]
Technically we're not published quite yet to homebrew-core, but I'll change the labels on this since the issue has mostly been resolved, aside from being 30 days old before we are officially published on homebrew-core. I'd like to keep this up just as a reminder when the time does come.

We will officially be 30 days old on August 11th, 2020

**Comment by TGotwig** [comment]
Can we also publish on [linuxbrew-core](https://github.com/Homebrew/linuxbrew-core)? 🍺🤠

**Comment by bee-san** [comment]
Hi there 👋🏻 

As of November 2024 the RustScan team has decided to remove all support for officially maintaining packages other than `Cargo`.

**Why?**

We are an incredibly small team and we found we were working more on fixing packages / the CI for packages rather than making RustScan a great tool.

**How will I use RustScan?**

RustScan is in many, many package managers already:
https://repology.org/project/rustscan/versions 

As well as on others like Snap https://snapcraft.io/rustscan or Docker https://hub.docker.com/search?q=rustscan and we may even be built into some pentesting distros by default.

If your favourite repo does not have a RustScan package, you are free to either make one or request one from them. RustScan is quite popular with thousands of GitHub stars and downloads, and it is incredibly easy to build (git clone && cargo build). We are sure that if we are not already distributed some way, it should not be hard to make a package.

**What about Cargo?**

Cargo will be our only officially supported package, as it's built into Rust by default and it's what our developers use.

If you want to use it, please install Rust and then run `cargo install rustscan`.
