### ISSUE TITLE
CI does not upload to crates

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#606]
The CI here:
https://github.com/RustScan/RustScan/blob/master/.github/workflows/release.yml#L213

No longer uploads to crate on release :( 

https://crates.io/crates/rustscan Crates has not updated in forever

There is definitely a CRATES_TOKEN too

**Comment by PsypherPunk** [comment]
Would the last release have been this one? https://github.com/RustScan/RustScan/actions/runs/8910878824

Looks like there was a homebrew-related error, stopping it at the previous step.
