### ISSUE TITLE
update yanked dependency

### ISSUE THREAD

**Issue by ognevny** [RustScan/RustScan#608]
**Describe the bug**
`libc 0.2.154` is yanked

**To Reproduce**
build with `--locked` option

**Expected behavior**
no warnings

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
``warning: package `libc v0.2.154` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked``

**Comment by bee-san** [comment]
thanks! we do not use libc in our cargo.toml, someone upstream from us uses it!
