### ISSUE TITLE
rustscan can not includes both discontinuous and continuous IP addresses

### ISSUE THREAD

**Issue by Archerkong** [RustScan/RustScan#625]
when i use rustscan to scan a ip with multi class ports ,it can not continue
my need scan ports:21,22,53,80,443,445,1080,2375,3333,3389,4433,4434,4443,4444,5003,5555,6666,7000-8999,9999,50050,60000
so i try some command:
└─# rustscan -a ip -p 21,22,53,80,443,445,1080,2375,3333,3389,4433,4434,4443,4444,5003,5555,6666,9999,50050,60000,7000-8999 
└─# rustscan -a ip -r 21,22,53,80,443,445,1080,2375,3333,3389,4433,4434,4443,4444,5003,5555,6666,9999,50050,60000,7000-8999 
the result is:
<img width="830" alt="image" src="https://github.com/user-attachments/assets/b55e431a-d445-4918-82cf-a0311c23fe01">

so i want to know how to resolve this,although I know rustscan is very fast to scan 1-65535

We look forward to your reply,thanks

**Comment by Athishpranav2003** [comment]
@Archerkong i guess -p command only supports comma seperated format and -r supports a-b format. Since you are giving both formats mixed thats why its not working

**Comment by PsypherPunk** [comment]
As @Athishpranav2003 said, this is how it's currently built: it's a binary choice between specific ports or a range (largely handled by the `PortStrategy`, looking at it).

It would be _possible_ to change it but at a cursory glance it'd be a reasonable (but not insurmountable) amount of work—what's the use-case?

**Comment by bee-san** [comment]
This ticket has been inactive for a while, closing.
