### ISSUE TITLE
Bring back --no-nmap! 

### ISSUE THREAD

**Issue by Apocryphon-X** [RustScan/RustScan#650]
**Is your feature request related to a problem?** 
Is it possible to disable nmap WITHOUT disabling the banner and other stuff? I can't find a way to do this and --greppable doesn't shows the live results, rustscan has to finish in order to see the results. Also everything else dissapears, the banner, the colors, the funny quotes, the notes, etc...

**Describe the solution you'd like**
Bring back --no-nmap :)

**Describe alternatives you've considered**
Doing Ctrl-C when nmap starts

**Comment by PsypherPunk** [comment]
@Apocryphon-X, is `--scripts none` what you're after? Or did `--no-nmap` do something else?

**Comment by Apocryphon-X** [comment]
Oh, actually that is what I was trying to achieve. Thank you! Maybe it is just a bit hard to find in the docs. (Hopefully this issue will serve as a reference for future people looking for the same thing)

I think I should close this as solved.
