### ISSUE TITLE
Add option to save output of command

### ISSUE THREAD

**Issue by AD2011** [RustScan/RustScan#666]
I am always frustrated when I save output of a scan of a large subnet using `tee outputfile.txt` and it saves with colours in the terminal and with high verbosity.
For example: 
[oneresults.txt](https://github.com/user-attachments/files/17281222/oneresults.txt)

Please provide an option to output results with no colour and low verbosity.

**Comment by PsypherPunk** [comment]
I think that's the intention of the `--greppable` flag—does that give the minimal output you're after?

**Comment by AD2011** [comment]
@PsypherPunk Yes, but nmap scans options doesn't work after `-g` or `--greppable` flag is active
![image](https://github.com/user-attachments/assets/f17ae465-0530-4b4b-a87c-d986b8267721)

**Comment by PsypherPunk** [comment]
Would `--accessible` be what you're after?

Suppresses most of the output and colours but includes the `nmap` output.

**Comment by bee-san** [comment]
This ticket has been inactive for a while, closing.
