### ISSUE TITLE
This is different from the fingerprints detected by Nmap. The fingerprint of Rustscan is incorrect.

### ISSUE THREAD

**Issue by TajangSec** [RustScan/RustScan#674]
**Describe the bug**
The fingerprint of Rustscan is incorrect.

**To Reproduce**
Nmap:
```
nmap -sV -p 6068 10.10.x.21
Starting Nmap 7.95 ( https://nmap.org ) at 2024-10-18 16:08
Nmap scan report for 10.10.x.21
Host is up (0.0029s latency).

PORT     STATE SERVICE    VERSION
6068/tcp open  postgresql PostgreSQL DB 9.6.4 - 9.6.6 or 9.6.13 - 9.6.19
```

Rustscan:
```
rustscan -a 10.10.x.21

PORT     STATE SERVICE REASON
6068/tcp open  gsmp    syn-ack ttl 58
```

In fact, Nmap is correct, and I don't understand why RustScan didn't detect such a clear database when it should have been using Nmap's fingerprint by default.

**Comment by BrendanGlancy** [comment]
Do you mind expanding on this so I can get a better idea of what you are talking about

**Comment by TajangSec** [comment]
> Do you mind expanding on this so I can get a better idea of what you are talking about

When scanning network assets, I need to know the asset type, such as what service is on port XX. When I use nmap, it can detect the PostgreSQL database, but rustscan identifies it as gsmp, which I don't understand and is not useful for my work. Rustscan uses nmap's scripts by default, so why are the results different?

**Comment by PsypherPunk** [comment]
Definitely odd as RustScan should just proxy this to `nmap`.

If you just run `nmap -p 6068 10.10.x.21` (i.e. without the `-sV`), do you see the same output as RustScan's version?

If so, I think that's down to the default parameters passed to `nmap` try:

```sh
rustscan -a 10.10.x.21 -- -sV
```

**Comment by bee-san** [comment]
This ticket has been inactive for a while, closing.
