### ISSUE TITLE
Argument to disable colors in output

### ISSUE THREAD

**Issue by mugiseyebrows** [RustScan/RustScan#677]
I'm on windows 10 and cmd terminal (and pwsh also) doesn't seem to support colors as shell escape codes (at least without tweaking).

It would be cool to have argument to disable colors in output like for example `--color=never`.

**Comment by deepdvd** [comment]
←[1m←[38;2;0;255;0m.←[38;2;0;255;6m-←[38;2;0;255;13m-←[38;2;0;255;19m-←[38;2;0;255;25m-←[38;2;0;255;32m.←[38;2;0;255;38m
 ←[38;2;0;255;45m.←[38;2;0;255;51m-←[38;2;0;255;57m.←[38;2;0;255;64m ←[38;2;0;255;70m.←[38;2;0;255;76m-←[38;2;0;255;83m.
←[38;2;0;255;89m ←[38;2;0;255;96m.←[38;2;0;255;102m-←[38;2;0;255;108m-←[38;2;0;255;115m-←[38;2;0;255;121m-←[38;2;0;255;1
27m.←[38;2;0;255;134m.←[38;2;0;255;140m-←[38;2;0;255;147m-←[38;2;0;255;153m-←[38;2;0;255;159m.←[38;2;0;255;166m ←[38;2;0
;255;172m ←[38;2;0;255;178m.←[38;2;0;255;185m-←[38;2;0;255;191m-←[38;2;0;255;198m-←[38;2;0;255;204m-←[38;2;0;255;210m.←[
38;2;0;255;217m ←[38;2;0;255;223m.←[38;2;0;255;229m-←[38;2;0;255;236m-←[38;2;0;255;242m-←[38;2;0;255;249m.←[38;2;0;255;2
55m ←[38;2;0;249;255m ←[38;2;0;242;255m ←[38;2;0;236;255m.←[38;2;0;230;255m-←[38;2;0;223;255m-←[38;2;0;217;255m.←[38;2;0
;210;255m ←[38;2;0;204;255m ←[38;2;0;198;255m.←[38;2;0;191;255m-←[38;2;0;185;255m.←[38;2;0;179;255m ←[38;2;0;172;255m.←[
38;2;0;166;255m-←[38;2;0;159;255m.←[0m
←[38;2;0;255;0m|←[38;2;0;255;6m ←[38;2;0;255;13m{←[38;2;0;255;19m}←[38;2;0;255;25m ←[38;2;0;255;32m ←[38;2;0;255;38m}←[3
8;2;0;255;45m|←[38;2;0;255;51m ←[38;2;0;255;57m{←[38;2;0;255;64m ←[38;2;0;255;70m}←[38;2;0;255;76m ←[38;2;0;255;83m|←[38
;2;0;255;89m{←[38;2;0;255;96m ←[38;2;0;255;102m{←[38;2;0;255;108m_←[38;2;0;255;115m_←[38;2;0;255;121m ←[38;2;0;255;127m{
←[38;2;0;255;134m_←[38;2;0;255;140m ←[38;2;0;255;147m ←[38;2;0;255;153m ←[38;2;0;255;159m_←[38;2;0;255;166m}←[38;2;0;255
;172m{←[38;2;0;255;178m ←[38;2;0;255;185m{←[38;2;0;255;191m_←[38;2;0;255;198m_←[38;2;0;255;204m ←[38;2;0;255;210m ←[38;2
;0;255;217m/←[38;2;0;255;223m ←[38;2;0;255;229m ←[38;2;0;255;236m_←[38;2;0;255;242m_←[38;2;0;255;249m_←[38;2;0;255;255m}
←[38;2;0;249;255m ←[38;2;0;242;255m/←[38;2;0;236;255m ←[38;2;0;230;255m{←[38;2;0;223;255m}←[38;2;0;217;255m ←[38;2;0;210
;255m\←[38;2;0;204;255m ←[38;2;0;198;255m|←[38;2;0;191;255m ←[38;2;0;185;255m ←[38;2;0;179;255m`←[38;2;0;172;255m|←[38;2
;0;166;255m ←[38;2;0;159;255m|←[0m
←[38;2;0;255;0m|←[38;2;0;255;6m ←[38;2;0;255;13m.←[38;2;0;255;19m-←[38;2;0;255;25m.←[38;2;0;255;32m ←[38;2;0;255;38m\←[3
8;2;0;255;45m|←[38;2;0;255;51m ←[38;2;0;255;57m{←[38;2;0;255;64m_←[38;2;0;255;70m}←[38;2;0;255;76m ←[38;2;0;255;83m|←[38
;2;0;255;89m.←[38;2;0;255;96m-←[38;2;0;255;102m.←[38;2;0;255;108m_←[38;2;0;255;115m}←[38;2;0;255;121m ←[38;2;0;255;127m}
←[38;2;0;255;134m ←[38;2;0;255;140m|←[38;2;0;255;147m ←[38;2;0;255;153m|←[38;2;0;255;159m ←[38;2;0;255;166m ←[38;2;0;255
;172m.←[38;2;0;255;178m-←[38;2;0;255;185m.←[38;2;0;255;191m_←[38;2;0;255;198m}←[38;2;0;255;204m ←[38;2;0;255;210m}←[38;2
;0;255;217m\←[38;2;0;255;223m ←[38;2;0;255;229m ←[38;2;0;255;236m ←[38;2;0;255;242m ←[38;2;0;255;249m ←[38;2;0;255;255m}
←[38;2;0;249;255m/←[38;2;0;242;255m ←[38;2;0;236;255m ←[38;2;0;230;255m/←[38;2;0;223;255m\←[38;2;0;217;255m ←[38;2;0;210
;255m ←[38;2;0;204;255m\←[38;2;0;198;255m|←[38;2;0;191;255m ←[38;2;0;185;255m|←[38;2;0;179;255m\←[38;2;0;172;255m ←[38;2
;0;166;255m ←[38;2;0;159;255m|←[0m
←[38;2;0;255;0m`←[38;2;0;255;6m-←[38;2;0;255;13m'←[38;2;0;255;19m ←[38;2;0;255;25m`←[38;2;0;255;32m-←[38;2;0;255;38m'←[3
8;2;0;255;45m`←[38;2;0;255;51m-←[38;2;0;255;57m-←[38;2;0;255;64m-←[38;2;0;255;70m-←[38;2;0;255;76m-←[38;2;0;255;83m'←[38
;2;0;255;89m`←[38;2;0;255;96m-←[38;2;0;255;102m-←[38;2;0;255;108m-←[38;2;0;255;115m-←[38;2;0;255;121m'←[38;2;0;255;127m
←[38;2;0;255;134m ←[38;2;0;255;140m`←[38;2;0;255;147m-←[38;2;0;255;153m'←[38;2;0;255;159m ←[38;2;0;255;166m ←[38;2;0;255
;172m`←[38;2;0;255;178m-←[38;2;0;255;185m-←[38;2;0;255;191m-←[38;2;0;255;198m-←[38;2;0;255;204m'←[38;2;0;255;210m ←[38;2
;0;255;217m ←[38;2;0;255;223m`←[38;2;0;255;229m-←[38;2;0;255;236m-←[38;2;0;255;242m-←[38;2;0;255;249m'←[38;2;0;255;255m
←[38;2;0;249;255m`←[38;2;0;242;255m-←[38;2;0;236;255m'←[38;2;0;230;255m ←[38;2;0;223;255m ←[38;2;0;217;255m`←[38;2;0;210
;255m-←[38;2;0;204;255m'←[38;2;0;198;255m`←[38;2;0;191;255m-←[38;2;0;185;255m'←[38;2;0;179;255m ←[38;2;0;172;255m`←[38;2
;0;166;255m-←[38;2;0;159;255m'←[0m
←[38;2;0;255;0mT←[38;2;0;255;6mh←[38;2;0;255;13me←[38;2;0;255;19m ←[38;2;0;255;25mM←[38;2;0;255;32mo←[38;2;0;255;38md←[3
8;2;0;255;45me←[38;2;0;255;51mr←[38;2;0;255;57mn←[38;2;0;255;64m ←[38;2;0;255;70mD←[38;2;0;255;76ma←[38;2;0;255;83my←[38
;2;0;255;89m ←[38;2;0;255;96mP←[38;2;0;255;102mo←[38;2;0;255;108mr←[38;2;0;255;115mt←[38;2;0;255;121m ←[38;2;0;255;127mS
←[38;2;0;255;134mc←[38;2;0;255;140ma←[38;2;0;255;147mn←[38;2;0;255;153mn←[38;2;0;255;159me←[38;2;0;255;166mr←[38;2;0;255
;172m.←[0m←[0m
←[1m←[38;2;255;255;0m_←[38;2;249;255;0m_←[38;2;242;255;0m_←[38;2;236;255;0m_←[38;2;230;255;0m_←[38;2;223;255;0m_←[38;2;2
17;255;0m_←[38;2;210;255;0m_←[38;2;204;255;0m_←[38;2;198;255;0m_←[38;2;191;255;0m_←[38;2;185;255;0m_←[38;2;179;255;0m_←[
38;2;172;255;0m_←[38;2;166;255;0m_←[38;2;159;255;0m_←[38;2;153;255;0m_←[38;2;147;255;0m_←[38;2;140;255;0m_←[38;2;134;255
;0m_←[38;2;128;255;0m_←[38;2;121;255;0m_←[38;2;115;255;0m_←[38;2;108;255;0m_←[38;2;102;255;0m_←[38;2;96;255;0m_←[38;2;89
;255;0m_←[38;2;83;255;0m_←[38;2;77;255;0m_←[38;2;70;255;0m_←[38;2;64;255;0m_←[38;2;57;255;0m_←[38;2;51;255;0m_←[38;2;45;
255;0m_←[38;2;38;255;0m_←[38;2;32;255;0m_←[38;2;26;255;0m_←[38;2;19;255;0m_←[38;2;13;255;0m_←[38;2;6;255;0m_←[0m
←[38;2;255;255;0m:←[38;2;249;255;0m ←[38;2;242;255;0mh←[38;2;236;255;0mt←[38;2;230;255;0mt←[38;2;223;255;0mp←[38;2;217;2
55;0m:←[38;2;210;255;0m/←[38;2;204;255;0m/←[38;2;198;255;0md←[38;2;191;255;0mi←[38;2;185;255;0ms←[38;2;179;255;0mc←[38;2
;172;255;0mo←[38;2;166;255;0mr←[38;2;159;255;0md←[38;2;153;255;0m.←[38;2;147;255;0ms←[38;2;140;255;0mk←[38;2;134;255;0me
←[38;2;128;255;0mr←[38;2;121;255;0mr←[38;2;115;255;0mi←[38;2;108;255;0mt←[38;2;102;255;0mt←[38;2;96;255;0m.←[38;2;89;255
;0mb←[38;2;83;255;0ml←[38;2;77;255;0mo←[38;2;70;255;0mg←[38;2;64;255;0m ←[38;2;57;255;0m ←[38;2;51;255;0m ←[38;2;45;255;
0m ←[38;2;38;255;0m ←[38;2;32;255;0m ←[38;2;26;255;0m ←[38;2;19;255;0m ←[38;2;13;255;0m ←[38;2;6;255;0m:←[0m
←[38;2;255;255;0m:←[38;2;249;255;0m ←[38;2;242;255;0mh←[38;2;236;255;0mt←[38;2;230;255;0mt←[38;2;223;255;0mp←[38;2;217;2
55;0ms←[38;2;210;255;0m:←[38;2;204;255;0m/←[38;2;198;255;0m/←[38;2;191;255;0mg←[38;2;185;255;0mi←[38;2;179;255;0mt←[38;2
;172;255;0mh←[38;2;166;255;0mu←[38;2;159;255;0mb←[38;2;153;255;0m.←[38;2;147;255;0mc←[38;2;140;255;0mo←[38;2;134;255;0mm
←[38;2;128;255;0m/←[38;2;121;255;0mR←[38;2;115;255;0mu←[38;2;108;255;0ms←[38;2;102;255;0mt←[38;2;96;255;0mS←[38;2;89;255
;0mc←[38;2;83;255;0ma←[38;2;77;255;0mn←[38;2;70;255;0m/←[38;2;64;255;0mR←[38;2;57;255;0mu←[38;2;51;255;0ms←[38;2;45;255;
0mt←[38;2;38;255;0mS←[38;2;32;255;0mc←[38;2;26;255;0ma←[38;2;19;255;0mn←[38;2;13;255;0m ←[38;2;6;255;0m:←[0m
←[38;2;255;255;0m ←[38;2;249;255;0m-←[38;2;242;255;0m-←[38;2;236;255;0m-←[38;2;230;255;0m-←[38;2;223;255;0m-←[38;2;217;2
55;0m-←[38;2;210;255;0m-←[38;2;204;255;0m-←[38;2;198;255;0m-←[38;2;191;255;0m-←[38;2;185;255;0m-←[38;2;179;255;0m-←[38;2
;172;255;0m-←[38;2;166;255;0m-←[38;2;159;255;0m-←[38;2;153;255;0m-←[38;2;147;255;0m-←[38;2;140;255;0m-←[38;2;134;255;0m-
←[38;2;128;255;0m-←[38;2;121;255;0m-←[38;2;115;255;0m-←[38;2;108;255;0m-←[38;2;102;255;0m-←[38;2;96;255;0m-←[38;2;89;255
;0m-←[38;2;83;255;0m-←[38;2;77;255;0m-←[38;2;70;255;0m-←[38;2;64;255;0m-←[38;2;57;255;0m-←[38;2;51;255;0m-←[38;2;45;255;
0m-←[38;2;38;255;0m-←[38;2;32;255;0m-←[38;2;26;255;0m-←[38;2;19;255;0m-←[38;2;13;255;0m-←[0m←[0m
RustScan: Where scanning meets swagging. 😎

I'm not expecting much support on the Windows side, but I think it either should be fixed to show the colors or given the option to turn off colors.  Is there a known tweak to fix it?
