### ISSUE TITLE
Rustscan doesn't find an open port and crashes

### ISSUE THREAD

**Issue by Outcalled** [RustScan/RustScan#689]
**Describe the bug**
When I run my ip ranges file, it keep saying "i didnt find any open ports for (example ip)"

**To Reproduce**
./rustscan -a "ip_ranges.txt" -p 5000,12233,6260  --scan-order random | tee outputfile.txt

**Expected behavior**
Looks like I didn't find any open ports for 3.140.xxx.xxx. This is usually caused by a high batch size.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by PsypherPunk** [comment]
Hi, @Outcalled. A few things to clarify: 

- is this the most recent version of RustScan?
- have you confirmed that there are actually open ports (e.g. via Nmap)?
- when you say "crashes", is there an error?

**Comment by bee-san** [comment]
No replies, closing ticket.
