### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by asarubbo** [RustScan/RustScan#690]
Hello,

I was trying to add RustScan in Gentoo, and while creating an ebuild I noticed the following test failures:

```
failures:

---- address::tests::resolver_args_google_dns stdout ----
thread 'address::tests::resolver_args_google_dns' panicked at src/address.rs:277:61:
called `Result::unwrap()` on an `Err` value: ResolveError { kind: Proto(ProtoError { kind: Io(Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }) }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- address::tests::parse_correct_host_addresses stdout ----
thread 'address::tests::parse_correct_host_addresses' panicked at src/address.rs:212:9:
assertion `left == right` failed
  left: 0
 right: 1

---- address::tests::resolver_default_cloudflare stdout ----
thread 'address::tests::resolver_default_cloudflare' panicked at src/address.rs:264:61:
called `Result::unwrap()` on an `Err` value: ResolveError { kind: Timeout }

---- address::tests::parse_hosts_file_and_incorrect_hosts stdout ----
thread 'address::tests::parse_hosts_file_and_incorrect_hosts' panicked at src/address.rs:238:9:
assertion `left == right` failed
  left: 1
 right: 3


failures:
    address::tests::parse_correct_host_addresses
    address::tests::parse_hosts_file_and_incorrect_hosts
    address::tests::resolver_args_google_dns
    address::tests::resolver_default_cloudflare

test result: FAILED. 40 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 90.07s
```

So, in Gentoo, by default, the sandbox does not allow you to use the network during tests, so `address::tests::resolver_args_google_dns stdout` fails for this reason.

Can you confirm if the other failing tests require the network?

I'm using v2.3.0 with rust-1.81.0

Thanks

**Comment by PsypherPunk** [comment]
Hi, @asarubbo. Yes, in every case it's relying on DNS resolution as part of the test.

Will this block you from packaging this?

**Comment by asarubbo** [comment]
> Hi, @asarubbo. Yes, in all of those cases it's relying on DNS resolution as part of the test.
> 
> Will this block you from packaging this?

Absolutely not. I have added a rule to skip those tests in case of `FEATURES=network-sandbox`

I have just another question:

I see a 'command not found' between two tests:

```
test scripts::tests::find_and_parse_scripts ... ok
sh: line 1: qwertyuiop: command not found
test scripts::tests::open_script_file_invalid_call_format - should panic ... ok
```

So, for the package manager it ends up as:
```
 * QA Notice: command not found:
 * 
 *      sh: line 1: qwertyuiop: command not found
 ```
 
 Can you clarify what is trying to do and/or if it is a mistake?

**Comment by PsypherPunk** [comment]
Yep, that's the `open_script_file_invalid_call_format()` test which is wrapped in a `#[should_panic]`: it's an intended/expected failure.

**Comment by asarubbo** [comment]
> Yep, that's the `open_script_file_invalid_call_format()` test which is wrapped in a `#[should_panic]`: it's an intended/expected failure.

In order to avoid bug reports about that, do you think is reasonable (and could work for the testcase) avoid to print the 'command not found' on stdout?

**Comment by PsypherPunk** [comment]
Raised #692 which should prevent that.
