### ISSUE TITLE
I dont want to run nmap after rustscan

### ISSUE THREAD

**Issue by iamRjarpan** [RustScan/RustScan#82]
I really love rustscan and I use it to scan cidr but it will be very useful If there is a option not to run nmap scan because nmap scan eat a lot of time.

**Comment by brandonskerritt** [comment]
Hey! This is already a feature, it's called "Quiet mode" and can be activated with `-q`. 

I just published the release (1.3) which contains this.

It is currently on Cargo `cargo install rustscan`, and will be distributed via AUR, Homebrew, and .deb as the day goes on.

If you are using one of these distributions, let me know and I'll speed up the process to get it to you faster :D

P.S: cidr support is coming after IPv6 :)

**Comment by brandonskerritt** [comment]
Deb file uploaded

**Comment by brandonskerritt** [comment]
Homebrew updated :)

**Comment by brandonskerritt** [comment]
Okay I'm having some problems with AUR and my ssh keys, gonna take a little bit longer than I expected to figure out what's going wrong... :stuck_out_tongue:

**Comment by brandonskerritt** [comment]
My bad, the AUR is moving servers:
https://lists.archlinux.org/pipermail/arch-dev-public/2020-July/030042.html
I need to re-config my SSH keys with the new AUR

**Comment by brandonskerritt** [comment]
All done!
