### ISSUE TITLE
Build CI to auto-distribute releases to homebrew, aur, and deb files

### ISSUE THREAD

**Issue by inainazumakun** [RustScan/RustScan#83]
Make life easier for updating RustScan version control.

**Comment by brandonskerritt** [comment]
We auto-distribute to AUR already. We need some way to upload .deb files to GitHub ci. In our root directory, Rust-DebBuilder is used to build the debian files run `run.sh` to build them :)

**Comment by PsypherPunk** [comment]
@bee-san, I've got some GitHub config. over [here](https://github.com/PsypherPunk/jargon-rs/blob/main/.github/workflows/release.yml) that does something similar:

* whenever you [tag a release](https://github.com/PsypherPunk/jargon-rs/blob/main/.github/workflows/release.yml#L4);
* it [builds a `.deb` file](https://github.com/PsypherPunk/jargon-rs/blob/main/.github/workflows/release.yml#L29);
* then [creates a new GitHub release](https://github.com/PsypherPunk/jargon-rs/blob/main/.github/workflows/release.yml#L66);
* then [uploads the `.deb`](https://github.com/PsypherPunk/jargon-rs/blob/main/.github/workflows/release.yml#L83) to the release.

However, I'm not sure how that fits into your current release-creation workflow. Happy to raise a PR if this is still of any use…?
