### ISSUE TITLE
Giving rustscan specific ports to scan

### ISSUE THREAD

**Issue by idangur** [RustScan/RustScan#85]
I think it will be really benefitial for me and surely for other people to list specific ports
for rustscan to scan, as a way to reduce network output of both nmap and rustscan.

Maybe as a json file argument or as an argument type, something like 21-23,80,443,445,700-1024, 
Just a thought and maybe i can check at how it can be implemented if wanted as a feature.

And i just wanted to say that the project can grow to be so much more and has a lot of potential!!!

**Comment by brandonskerritt** [comment]
Hey!!!

Thanks for your kind words :D 

I'm planning on adding port ranges, maybe in JSON format;
Something like:

```
IP: 80, 443, 8080
CIDR rane: 1-65535
```

So users can control exactly what gets scanned from what IP addresses :D 

Right now I'm rewriting how we deal with IP addresses, and then I'll add CIDR support and eventually individual port support :)

**Comment by bernardoamc** [comment]
Somehow I think this would fit really well in a `toml` file format akin to our `Cargo.toml`. What do you think? :)

**Comment by brandonskerritt** [comment]
> Somehow I think this would fit really well in a `toml` file format akin to our `Cargo.toml`. What do you think? :)

Perfect! I'll move it over there :D
