### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#88]
**Describe the solution you'd like**
Progress bars that show progress would be neato

**Additional context**
https://crates.io/crates/indicatif

**Comment by mattcorbin** [comment]
I'd like to give this one a shot, may take me a while though

**Comment by brightly-salty** [comment]
I'm assuming this should be closed, as mattcorbin's pull request has been merged? (Just asking because when I filtered the issues by "good first issue", this one still shows up when it probably shouldn't)

**Comment by mattcorbin** [comment]
The PR was closed, not merged, but based on https://github.com/RustScan/RustScan/pull/184#issuecomment-703287529 I think this issue should probably be closed anyways.

**Comment by dkasak** [comment]
I just came looking for a progress bar issue as it's quite disorienting not to have any indication of the progress and I don't quite understanding the reasoning in that comment. @bee-san, why do different types of scans / scripts prevent a progress bar implementation?
