### ISSUE TITLE
Failing Documentation

### ISSUE THREAD

**Issue by brandonskerritt** [RustScan/RustScan#89]
**Describe the bug**
We have doc comments in the code, but we're not appearing on https://docs.rs

I believe we should automatically be added when we publish to Cargo, in this case we are not.

**To Reproduce**
https://docs.rs/releases/search?query=rustscan

**Expected behavior**
We appear on the docs site.

**Comment by remigourdon** [comment]
Hi @brandonskerritt !

I was looking at taking up that one as my first contribution. After doing some research on the Discord, it seems to me like this is most likely due to the fact that the crate is a pure binary, and [docs.rs](https://docs.rs) does not generate documentation for those. See for example [this issue](https://github.com/rust-lang/docs.rs/issues/644).

I suppose the best way to solve this issue would be to move the code into a library and using this lib's functionality from within `main.rs`.

**Comment by brandonskerritt** [comment]
Hey!!! Thanks so much for sharing. We do want to move towards more of a tool that can be used in other tools, rather than a single binary tool on its own.

For now, we might be able to store the documentation on GitHub pages or something, as we can generate documentation just fine.

If I am honest with you, I know little about Rust libraries. But GitHub pages seems to be the best way.

This looks promising, but the blog doesn't render properly in my browser.
https://hoverbear.org/blog/rust-travis-github-pages/

If at all possible, can you look at the best way for us to deploy docs onto Github pages, if that is easier? We can use either GitHub actions or Travis CI. 

If you need some tokens / API keys or whatever, let me know and I can add them to the repos secrets. 

**Thank you** for looking into the issue for us :D Without you, we would be continually banging our heads wondering why the documentation didn't work :sweat_smile: 

Hope to see you around more :sparkles:

**Comment by remigourdon** [comment]
Hi!

I will have a look at how to proceed for Github pages hosting and get back to you. I have actually been wondering myself how to do this on Gitlab Pages recently for another Rust project, so that should help me solve the 2 problems at once.

**Comment by andy5995** [comment]
> If I am honest with you, I know little about Rust libraries.

There's very little difference between a Rust library and a binary. The code is the same, there's just a few minor differences as to how it's structured.

If you ever feel like experimenting, try this:

Start a new lib project with with the `--lib` option of cargo. Call it "hello_world_lib"

Edit src/lib.rs to add a function that returns the string "Hello World". It can have any name other than main(). The function will need to be public for a bin to access it. Run `cargo check` to make sure it builds.

Now outside of that directory, use cargo with the `bin` option to create a new bin project.

In Cargo.toml, add the dependency of the library you just created.

```ini
[dependencies]
hello_world_lib = { path = "../hello_world_lib" }
```

Now in main, call the function from the library. iirc, at that point I think all you need to do to call the function is precede the name with the library name and `::`. (e.g.  hello_world_lib::funcname())

**Comment by spenserblack** [comment]
Just an FYI, [RustScan is actually on docs.rs](https://docs.rs/crate/rustscan/1.7.1) (<-- redirected from https://docs.rs/rustscan)

Nothing is there, though (not even the README!), since, as previously stated, RustScan is not a library.
