### ISSUE TITLE
output/pipe results to a default file and specify the file format.

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#90]
I think that adding the option to add to output/pipe results to a default file and specify the file format.

Something like:
```
output:
	file: /path/to/file.extension (json/xml/txt)
	type: append / write
```

so you can monitor the file for logs and send them to splunk/elk would be really nice to have as a qos feature

_Originally posted by @idangur in https://github.com/RustScan/RustScan/issues/71#issuecomment-667345531_

**Comment by smackhack** [comment]
Additionally, it would be a pretty cool/useful idea to make a `.last_scan` that converts the last performed scan into a RustScan `.config` that you can export into a new .config or repeat the last performed scan with.

**Comment by Marshall-Hallenbeck** [comment]
Either allowing nmap to output all the results to a single file, or reintroducing the `--no-nmap` option so we can nmap the results would be nice. As it stands, there's no good way to save the output as if you pass in an output option to nmap, it overwrites the file.
