### ISSUE TITLE
Port RustScan to Docker Images

### ISSUE THREAD

**Issue by CMNatic** [RustScan/RustScan#98]
**Is your feature request related to a problem? Please describe.**
Port the entire installation process to docker images. At the moment, you gotta install rust & cargo for a singular project. Also, the docker image to build the `.deb` is 2.6GB~alone

**Describe the solution you'd like**
Installing RustScan, cargo dependencies and `nmap` in minimal docker images so they can be pulled and arguments parsed at the command line.

**Current Features:**

- [ ] Dockerfile also installs dependencies based upon the architecture (i.e. amd64, i3686, arm64)
- [ ] Debian-Buster image is 692MB and can be run in one command, over the builder that is 2.6GB where a .deb then needs to be installed
- [ ] Builds latest _successful_ cargo release (and from source) so no Dockerfile maintenance for newer versions
- [ ] Arguments can be parsed in one docker pull command
- [ ] De-restricts OS ulimit use `ulimit -n 100000;`

TODO / QoL:
- [ ] Port to Alpine
- [ ] Become more familiar with rust & cargo to further minimise and decrease build time (~4 mins)
- [ ] Allow ulimit to be enabled / disabled (increased ulimit uses more resources on host that's running the container)

**Describe alternatives you've considered**
None.

**Additional context**

Docker image size: 
![image](https://user-images.githubusercontent.com/4163116/89112919-2d4b1400-d462-11ea-8ce1-986d03902ae0.png)

Usage: 
![image](https://user-images.githubusercontent.com/4163116/89113044-9717ed80-d463-11ea-99f1-275dba441906.png)

**Comment by Hydragyrum** [comment]
Left an alpine-based dockerfile which uses the rust image to build, and a baseline alpine to run in #118

**Comment by Hydragyrum** [comment]
It's a bit smaller though :)
![image](https://user-images.githubusercontent.com/4928181/89346543-85c02280-d6a9-11ea-92bc-15641806ccc6.png)

**Comment by CMNatic** [comment]
Think this can be closed now that we've got a Dockerfile in place from #118  and a published image (albeit not CI'd _just_ yet)
