### ISSUE TITLE
Adding output and scanning list of hosts feature 

### ISSUE THREAD

**Issue by omaramin17** [RustScan/RustScan#99]
I think that adding an output flag with multiple file format would be useful to be like :
```
rustscan -b 500  192.168.1.1 -o output.txt

``` 

+ Ability to scan list of IPs with -iL flag 

I hope to see those options in next releases 🥳

**Comment by brandonskerritt** [comment]
Hey!

We already support this, just -- only on OS' which also support it.

To get just the ports RustScan finds as a file:

```
rustscan 127.0.0.1 -q > out.txtt
```

And for Nmap:

```
rustscan 127.0.0.1 -- -o output.txt
```

Ability to scan list of ports is coming, although the very first version will likely not be a file. We're discussing this over in #34 :)
